// emu-alltest engines (plan step 1.9): one self-generated thunk, byte-identical in two engines.
//   * host CPU  - hardware reference; only snippets generated by this program ever run natively
//   * Unicorn   - our QEMU 7.2.22 branch (UC_CPU_X86_MAX: every feature the translator implements)
// The thunk loads the full input state (GPRs, RFLAGS, FXSAVE image = x87 + MXCSR + XMM, YMM upper
// halves, a test stack and a 64 KiB operand region), runs the snippet, and saves the full output
// state (+ FNSTENV for the full x87 tag word). Faults are recorded (native: vectored exception
// handler; Unicorn: UC_HOOK_INTR / UC_HOOK_INSN_INVALID / unmapped-memory hooks) and both engines
// resume at the same save-state epilogue.
// Derived from the plan-1.6 backport harness (tag backport-tests-1.6).
#pragma once
#include <unicorn/unicorn.h>
#include <keystone/keystone.h>
#include <windows.h>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

namespace at
{
	// ── fixed layout (identical in both engines) ─────────────────────────────────────────────
	constexpr uint64_t CODE = 0x30000000, CODE_SIZE = 0x10000;
	constexpr uint64_t DATA = 0x30010000, DATA_SIZE = 0x10000;     // state blocks, stacks
	constexpr uint64_t MEM = 0x30020000, MEM_SIZE = 0x10000;       // operand memory (compared)
	constexpr uint64_t IN_BLK = DATA + 0x0000, OUT_BLK = DATA + 0x1000, HOST = DATA + 0x2000;
	constexpr uint64_t STACK_LO = DATA + 0x3000, STACK_TOP = DATA + 0x3F00;
	constexpr uint64_t EPI_STACK = DATA + 0x6000;
	constexpr uint64_t MEM_PTR = MEM + 0x8000;                       // rsi / r14: [rsi], [rsi+rcx]
	constexpr uint64_t MEM_DST = MEM + 0x9000;                       // rdi: string destination

	constexpr uint64_t S_GPR = 0x000, S_RFLAGS = 0x080, S_FX = 0x100, S_YMMH = 0x300, S_ENV = 0x400;

	enum reg { RAX, RCX, RDX, RBX, RSP, RBP, RSI, RDI, R8, R9, R10, R11, R12, R13, R14, R15 };
	inline const char* reg_name( int i )
	{
		static const char* n[] = { "rax","rcx","rdx","rbx","rsp","rbp","rsi","rdi","r8","r9","r10","r11","r12","r13","r14","r15" };
		return n[ i ];
	}

	struct state
	{
		uint64_t gpr[ 16 ];
		uint64_t rflags;
		uint8_t fx[ 512 ];
		uint8_t ymmh[ 16 ][ 16 ];
		uint8_t env[ 28 ];
		// AVX-512 state outside the thunk's XMM/YMM image: only the Unicorn engine moves it (code
		// hooks at the snippet's first instruction and at the epilogue, ext_regs = true); the host
		// CPU has no AVX-512, so the native engine leaves these zero
		uint8_t zmmh[ 16 ][ 32 ];   // ZMM0-15 bits 511:256
		uint8_t zmmx[ 16 ][ 64 ];   // ZMM16-31 bits 511:0
		uint64_t k[ 8 ];            // opmask K0-K7
		uint8_t stack[ STACK_TOP - STACK_LO ];
		uint8_t mem[ MEM_SIZE ];

		uint16_t fcw() const { uint16_t v; std::memcpy( &v, fx + 0, 2 ); return v; }
		uint16_t fsw() const { uint16_t v; std::memcpy( &v, fx + 2, 2 ); return v; }
		uint8_t ftw_abridged() const { return fx[ 4 ]; }
		uint16_t ftw_full() const { uint16_t v; std::memcpy( &v, env + 8, 2 ); return v; }
		uint32_t mxcsr() const { uint32_t v; std::memcpy( &v, fx + 24, 4 ); return v; }
		const uint8_t* st( int i ) const { return fx + 32 + i * 16; }
		const uint8_t* xmm( int i ) const { return fx + 160 + i * 16; }
	};

	struct result
	{
		std::unique_ptr<state> s = std::make_unique<state>();
		bool ran = false;
		bool faulted = false;
		int vector = -1;            // x86 vector; Unicorn exact, native mapped from the NTSTATUS
		uint64_t fault_rip = 0;
		std::string err;
	};

	inline std::string hx( uint64_t v ) { char b[ 24 ]; std::snprintf( b, sizeof( b ), "0x%llX", ( unsigned long long ) v ); return b; }

	// ── assembling (self-generated code only) ───────────────────────────────────────────────
	inline std::vector<uint8_t> assemble( const std::string& text, uint64_t addr, std::string* err = nullptr )
	{
		ks_engine* ks = nullptr;
		std::vector<uint8_t> out;
		if ( ks_open( KS_ARCH_X86, KS_MODE_64, &ks ) != KS_ERR_OK ) { if ( err ) *err = "ks_open"; return out; }
		unsigned char* enc = nullptr;
		size_t size = 0, count = 0;
		if ( ks_asm( ks, text.c_str(), addr, &enc, &size, &count ) != KS_ERR_OK ) { if ( err ) *err = ks_strerror( ks_errno( ks ) ); }
		else out.assign( enc, enc + size );
		if ( enc ) ks_free( enc );
		ks_close( ks );
		return out;
	}

	// Keystone encodes an absolute [imm] operand as RIP-relative in 64-bit mode, so all state
	// accesses go through rax = DATA.
	inline std::string at( uint64_t addr ) { return "[rax + " + hx( addr - DATA ) + "]"; }

	inline std::string prologue_text()
	{
		std::string s = "mov rax, " + hx( DATA ) + "\n";
		const char* hs[] = { "rbx", "rbp", "rdi", "rsi", "r12", "r13", "r14", "r15" };
		for ( int i = 0; i < 8; ++i ) s += "mov qword ptr " + at( HOST + i * 8 ) + ", " + hs[ i ] + "\n";
		s += "mov qword ptr " + at( HOST + 0x40 ) + ", rsp\n";
		s += "fnstcw word ptr " + at( HOST + 0x48 ) + "\nstmxcsr dword ptr " + at( HOST + 0x4C ) + "\n";
		for ( int i = 6; i < 16; ++i ) s += "movdqu xmmword ptr " + at( HOST + 0x80 + ( i - 6 ) * 16 ) + ", xmm" + std::to_string( i ) + "\n";
		s += "mov rsp, qword ptr " + at( IN_BLK + S_GPR + RSP * 8 ) + "\n";
		s += "fxrstor64 " + at( IN_BLK + S_FX ) + "\n";
		for ( int i = 0; i < 16; ++i )
			s += "vinserti128 ymm" + std::to_string( i ) + ", ymm" + std::to_string( i ) + ", xmmword ptr " + at( IN_BLK + S_YMMH + i * 16 ) + ", 1\n";
		s += "push qword ptr " + at( IN_BLK + S_RFLAGS ) + "\npopfq\n";
		for ( int i = 1; i < 16; ++i )
			if ( i != RSP ) s += std::string( "mov " ) + reg_name( i ) + ", qword ptr " + at( IN_BLK + S_GPR + i * 8 ) + "\n";
		s += "mov rax, qword ptr " + at( IN_BLK + S_GPR + RAX * 8 ) + "\n";
		return s;
	}

	inline std::string epilogue_text()   // follows the raw "mov [moffs64], rax"
	{
		std::string s = "mov rax, " + hx( DATA ) + "\n";
		for ( int i = 1; i < 16; ++i ) s += "mov qword ptr " + at( OUT_BLK + S_GPR + i * 8 ) + ", " + reg_name( i ) + "\n";
		s += "mov rsp, " + hx( EPI_STACK ) + "\npushfq\npop qword ptr " + at( OUT_BLK + S_RFLAGS ) + "\npush 0x202\npopfq\n";
		s += "fxsave64 " + at( OUT_BLK + S_FX ) + "\n";
		for ( int i = 0; i < 16; ++i )
			s += "vextracti128 xmmword ptr " + at( OUT_BLK + S_YMMH + i * 16 ) + ", ymm" + std::to_string( i ) + ", 1\n";
		s += "fnstenv " + at( OUT_BLK + S_ENV ) + "\nfninit\n";
		s += "fldcw word ptr " + at( HOST + 0x48 ) + "\nldmxcsr dword ptr " + at( HOST + 0x4C ) + "\n";
		const char* hs[] = { "rbx", "rbp", "rdi", "rsi", "r12", "r13", "r14", "r15" };
		for ( int i = 0; i < 8; ++i ) s += std::string( "mov " ) + hs[ i ] + ", qword ptr " + at( HOST + i * 8 ) + "\n";
		for ( int i = 6; i < 16; ++i ) s += "movdqu xmm" + std::to_string( i ) + ", xmmword ptr " + at( HOST + 0x80 + ( i - 6 ) * 16 ) + "\n";
		s += "mov rsp, qword ptr " + at( HOST + 0x40 ) + "\nvzeroupper\nret\n";
		return s;
	}

	struct program
	{
		std::vector<uint8_t> code;
		uint64_t snippet_begin = 0, snippet_end = 0, epilogue_at = 0, ret_at = 0;
	};

	// The prologue is fixed; the epilogue only depends on where it starts. Both are assembled
	// once per snippet length and cached.
	inline program build( const std::vector<uint8_t>& snippet, std::string* err )
	{
		static std::vector<uint8_t> pro = assemble( prologue_text(), CODE, err );
		static std::vector<std::vector<uint8_t>> epi_cache( 64 );
		program p;
		if ( pro.empty() || snippet.size() >= epi_cache.size() ) return p;
		uint64_t epi_addr = CODE + pro.size() + snippet.size();
		auto& epi = epi_cache[ snippet.size() ];
		if ( epi.empty() )
		{
			epi = { 0x48, 0xA3 };   // mov [moffs64], rax  - a true absolute store of the guest rax
			for ( int i = 0; i < 8; ++i ) epi.push_back( uint8_t( ( OUT_BLK + S_GPR ) >> ( 8 * i ) ) );
			std::vector<uint8_t> rest = assemble( epilogue_text(), epi_addr + epi.size(), err );
			if ( rest.empty() ) { epi.clear(); return p; }
			epi.insert( epi.end(), rest.begin(), rest.end() );
		}
		p.code = pro;
		p.code.insert( p.code.end(), snippet.begin(), snippet.end() );
		p.code.insert( p.code.end(), epi.begin(), epi.end() );
		p.snippet_begin = CODE + pro.size();
		p.snippet_end = p.epilogue_at = epi_addr;
		p.ret_at = CODE + p.code.size() - 1;
		return p;
	}

	inline void write_blocks( uint8_t* data, uint8_t* mem, const state& s )
	{
		uint8_t* in = data + ( IN_BLK - DATA );
		std::memset( in, 0, 0x1000 );
		std::memcpy( in + S_GPR, s.gpr, sizeof( s.gpr ) );
		std::memcpy( in + S_RFLAGS, &s.rflags, 8 );
		std::memcpy( in + S_FX, s.fx, 512 );
		std::memcpy( in + S_YMMH, s.ymmh, sizeof( s.ymmh ) );
		std::memcpy( data + ( STACK_LO - DATA ), s.stack, sizeof( s.stack ) );
		std::memcpy( mem, s.mem, MEM_SIZE );
	}

	inline void read_blocks( const uint8_t* data, const uint8_t* mem, state& s )
	{
		const uint8_t* out = data + ( OUT_BLK - DATA );
		std::memcpy( s.gpr, out + S_GPR, sizeof( s.gpr ) );
		std::memcpy( &s.rflags, out + S_RFLAGS, 8 );
		std::memcpy( s.fx, out + S_FX, 512 );
		std::memcpy( s.ymmh, out + S_YMMH, sizeof( s.ymmh ) );
		std::memcpy( s.env, out + S_ENV, sizeof( s.env ) );
		std::memcpy( s.stack, data + ( STACK_LO - DATA ), sizeof( s.stack ) );
		std::memcpy( s.mem, mem, MEM_SIZE );
	}

	// ── host CPU (self-generated code only) ─────────────────────────────────────────────────
	class native_engine
	{
	public:
		bool open( std::string& err )
		{
			code_ = ( uint8_t* ) VirtualAlloc( ( void* ) CODE, CODE_SIZE, MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE );
			data_ = ( uint8_t* ) VirtualAlloc( ( void* ) DATA, DATA_SIZE, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE );
			mem_ = ( uint8_t* ) VirtualAlloc( ( void* ) MEM, MEM_SIZE, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE );
			if ( code_ != ( void* ) CODE || data_ != ( void* ) DATA || mem_ != ( void* ) MEM ) { err = "VirtualAlloc at the fixed addresses failed"; return false; }
			veh_ = AddVectoredExceptionHandler( 1, veh );
			return true;
		}
		~native_engine()
		{
			if ( veh_ ) RemoveVectoredExceptionHandler( veh_ );
			for ( void* p : { ( void* ) code_, ( void* ) data_, ( void* ) mem_ } ) if ( p ) VirtualFree( p, 0, MEM_RELEASE );
		}
		void run( const program& p, const state& in, result& r )
		{
			std::memset( code_, 0xCC, CODE_SIZE );
			std::memcpy( code_, p.code.data(), p.code.size() );
			FlushInstructionCache( GetCurrentProcess(), code_, CODE_SIZE );
			std::memset( data_, 0, DATA_SIZE );
			write_blocks( data_, mem_, in );
			g().lo = p.snippet_begin; g().hi = p.snippet_end; g().resume = p.epilogue_at;
			g().faulted = false; g().code = 0; g().rip = 0;
			( ( void( * )() ) code_ )();
			r.ran = true;
			r.faulted = g().faulted;
			r.vector = g().faulted ? vector_of( g().code, g().info1 ) : -1;
			// Windows reports #MF and #XM with the same STATUS_FLOAT_* codes: an x87 opcode
			// (D8-DF, or FWAIT 9B) at the faulting RIP is #MF (16), anything else #XM (19)
			if ( r.vector == 16 && g().rip >= ( uint64_t ) code_ && g().rip < ( uint64_t ) code_ + CODE_SIZE )
			{
				const uint8_t* q = ( const uint8_t* ) g().rip;
				while ( *q == 0x66 || *q == 0x67 || *q == 0xF2 || *q == 0xF3 || ( *q & 0xF0 ) == 0x40 ) ++q;
				if ( !( ( *q >= 0xD8 && *q <= 0xDF ) || *q == 0x9B ) ) r.vector = 19;
			}
			r.fault_rip = g().rip;
			read_blocks( data_, mem_, *r.s );
		}
	private:
		struct globals { uint64_t lo, hi, resume, rip, info1; DWORD code; bool faulted; };
		static globals& g() { static globals x{}; return x; }
		static LONG CALLBACK veh( EXCEPTION_POINTERS* ep )
		{
			uint64_t rip = ep->ContextRecord->Rip;
			if ( rip < g().lo || rip >= g().hi ) return EXCEPTION_CONTINUE_SEARCH;
			g().faulted = true;
			g().code = ep->ExceptionRecord->ExceptionCode;
			g().info1 = ep->ExceptionRecord->NumberParameters >= 2 ? ep->ExceptionRecord->ExceptionInformation[ 1 ] : 0;
			g().rip = rip;
			// a trap (single step) leaves TF set in the context: clear it before resuming
			ep->ContextRecord->EFlags &= ~0x100u;
			ep->ContextRecord->Rip = g().resume;
			return EXCEPTION_CONTINUE_EXECUTION;
		}
		static int vector_of( DWORD code, uint64_t info1 )
		{
			switch ( code )
			{
				case STATUS_INTEGER_DIVIDE_BY_ZERO: case STATUS_INTEGER_OVERFLOW: return 0;
				case STATUS_SINGLE_STEP: return 1;
				case STATUS_BREAKPOINT: return 3;
				case STATUS_ILLEGAL_INSTRUCTION: return 6;
				case STATUS_PRIVILEGED_INSTRUCTION: return 13;
				case STATUS_ACCESS_VIOLATION: return info1 == ~0ull ? 13 : 14;   // #GP reports address -1
				case STATUS_DATATYPE_MISALIGNMENT: return 17;
				case STATUS_FLOAT_MULTIPLE_FAULTS: case STATUS_FLOAT_MULTIPLE_TRAPS: return 19;
				case STATUS_FLOAT_INVALID_OPERATION: case STATUS_FLOAT_DIVIDE_BY_ZERO: case STATUS_FLOAT_OVERFLOW:
				case STATUS_FLOAT_UNDERFLOW: case STATUS_FLOAT_INEXACT_RESULT: case STATUS_FLOAT_DENORMAL_OPERAND:
				case STATUS_FLOAT_STACK_CHECK: return 16;
				default: return 100 + int( code & 0xFF );
			}
		}
		uint8_t* code_ = nullptr; uint8_t* data_ = nullptr; uint8_t* mem_ = nullptr;
		PVOID veh_ = nullptr;
	};

	// ── Unicorn ─────────────────────────────────────────────────────────────────────────────
	class unicorn_engine
	{
	public:
		explicit unicorn_engine( int model, uint32_t quirks = 0 ) : model_( model ), quirks_( quirks ) {}
		// one engine per form (fresh translation cache), reused across that form's iterations
		bool load( const program& p, std::string& err )
		{
			close();
			uc_err e = uc_open( UC_ARCH_X86, UC_MODE_64, &uc_ );
			if ( e ) { err = std::string( "uc_open: " ) + uc_strerror( e ); return false; }
			uc_ctl_set_cpu_model( uc_, model_ );
			if ( quirks_ ) uc_ctl_set_x86_hw_quirks( uc_, quirks_ );
			// optional CPUID profile / strict-#UD / XCR0 (emu-alltest --cpuid/--strict/--xcr0)
			if ( !cpuid.empty() ) uc_ctl_set_x86_cpuid( uc_, cpuid.data(), cpuid.size() );
			if ( strict ) uc_ctl_set_x86_cpuid_strict( uc_, 1 );
			if ( xcr0 ) uc_reg_write( uc_, UC_X86_REG_XCR0, &xcr0 );
			if ( cr0 ) uc_reg_write( uc_, UC_X86_REG_CR0, &cr0 );
			uc_mem_map( uc_, CODE, CODE_SIZE, UC_PROT_ALL );
			uc_mem_map( uc_, DATA, DATA_SIZE, UC_PROT_READ | UC_PROT_WRITE );
			uc_mem_map( uc_, MEM, MEM_SIZE, UC_PROT_READ | UC_PROT_WRITE );
			uc_mem_write( uc_, CODE, p.code.data(), p.code.size() );
			uc_hook h;
			uc_hook_add( uc_, &h, UC_HOOK_INTR, ( void* ) on_intr, this, 1, 0 );
			uc_hook_add( uc_, &h, UC_HOOK_INSN_INVALID, ( void* ) on_invalid, this, 1, 0 );
			uc_hook_add( uc_, &h, UC_HOOK_MEM_UNMAPPED, ( void* ) on_unmapped, this, 1, 0 );
			if ( ext_regs )
			{
				// ZMM0-31 / K0-7 in at the snippet's first instruction, out at the epilogue's first
				// instruction (the prologue's VEX loads zero ZMM bits 511:256, the epilogue's
				// VZEROUPPER would zero them again)
				uc_hook_add( uc_, &h, UC_HOOK_CODE, ( void* ) on_ext, this, p.snippet_begin, p.snippet_begin );
				if ( p.epilogue_at != p.snippet_begin )
					uc_hook_add( uc_, &h, UC_HOOK_CODE, ( void* ) on_ext, this, p.epilogue_at, p.epilogue_at );
			}
			prog_ = &p;
			return true;
		}
		~unicorn_engine() { close(); }
		void run( const state& in, result& r )
		{
			std::vector<uint8_t> data( DATA_SIZE, 0 ), mem( MEM_SIZE );
			write_blocks( data.data(), mem.data(), in );
			uc_mem_write( uc_, DATA, data.data(), data.size() );
			uc_mem_write( uc_, MEM, mem.data(), mem.size() );
			uint64_t rsp = HOST + 0x800;
			uc_reg_write( uc_, UC_X86_REG_RSP, &rsp );
			cur_ = &r;
			in_ = &in;
			ext_in_done_ = ext_out_done_ = false;
			pending_epilogue_ = false;
			uc_err e = uc_emu_start( uc_, CODE, prog_->ret_at, 0, 0 );
			if ( e && pending_epilogue_ )
			{
				// an unmapped access inside the snippet stopped the run (#PF): save the state at
				// the faulting instruction by running the epilogue, as the native VEH path does
				e = uc_emu_start( uc_, prog_->epilogue_at, prog_->ret_at, 0, 0 );
			}
			if ( e ) r.err = std::string( "uc_emu_start: " ) + uc_strerror( e );
			uc_mem_read( uc_, DATA, data.data(), data.size() );
			uc_mem_read( uc_, MEM, mem.data(), mem.size() );
			read_blocks( data.data(), mem.data(), *r.s );
			r.ran = !e;
			if ( ext_regs && !ext_out_done_ && r.err.empty() ) r.err = "epilogue not reached: ZMM/K state not read";
			cur_ = nullptr;
			in_ = nullptr;
		}
	private:
		void close() { if ( uc_ ) uc_close( uc_ ); uc_ = nullptr; }
		void fault( uint64_t rip, int vec )
		{
			if ( !cur_->faulted ) { cur_->faulted = true; cur_->vector = vec; cur_->fault_rip = rip; }
		}
		bool resume_if_in_snippet( uint64_t rip )
		{
			if ( rip < prog_->snippet_begin || rip >= prog_->snippet_end ) return false;
			uint64_t to = prog_->epilogue_at;
			uc_reg_write( uc_, UC_X86_REG_RIP, &to );
			// clear TF so a single-step trap does not repeat inside the epilogue
			uint64_t fl = 0; uc_reg_read( uc_, UC_X86_REG_RFLAGS, &fl ); fl &= ~0x100ull; uc_reg_write( uc_, UC_X86_REG_RFLAGS, &fl );
			return true;
		}
		static void on_intr( uc_engine* uc, uint32_t intno, void* user )
		{
			auto* self = ( unicorn_engine* ) user;
			uint64_t rip = 0; uc_reg_read( uc, UC_X86_REG_RIP, &rip );
			self->fault( rip, int( intno ) );
			if ( !self->resume_if_in_snippet( rip ) ) uc_emu_stop( uc );
		}
		static bool on_invalid( uc_engine* uc, void* user )
		{
			auto* self = ( unicorn_engine* ) user;
			uint64_t rip = 0; uc_reg_read( uc, UC_X86_REG_RIP, &rip );
			self->fault( rip, 6 );
			return self->resume_if_in_snippet( rip );
		}
		static bool on_unmapped( uc_engine* uc, uc_mem_type, uint64_t, int, int64_t, void* user )
		{
			// an access outside our regions: the host sees an access violation (#PF) there too
			auto* self = ( unicorn_engine* ) user;
			uint64_t rip = 0; uc_reg_read( uc, UC_X86_REG_RIP, &rip );
			self->fault( rip, 14 );
			if ( rip >= self->prog_->snippet_begin && rip < self->prog_->snippet_end ) self->pending_epilogue_ = true;
			return false;
		}
		static void on_ext( uc_engine* uc, uint64_t addr, uint32_t, void* user )
		{
			auto* self = ( unicorn_engine* ) user;
			if ( !self->cur_ || !self->in_ ) return;
			if ( addr == self->prog_->snippet_begin && !self->ext_in_done_ )
			{
				self->ext_in_done_ = true;
				const state& in = *self->in_;
				for ( int i = 0; i < 32; ++i )
				{
					uint8_t z[ 64 ];
					if ( i < 16 )
					{
						std::memcpy( z, in.xmm( i ), 16 );
						std::memcpy( z + 16, in.ymmh[ i ], 16 );
						std::memcpy( z + 32, in.zmmh[ i ], 32 );
					}
					else std::memcpy( z, in.zmmx[ i - 16 ], 64 );
					if ( uc_reg_write( uc, UC_X86_REG_ZMM0 + i, z ) != UC_ERR_OK ) self->ext_err( "uc_reg_write ZMM" + std::to_string( i ) );
				}
				for ( int i = 0; i < 8; ++i )
					if ( uc_reg_write( uc, UC_X86_REG_K0 + i, &in.k[ i ] ) != UC_ERR_OK ) self->ext_err( "uc_reg_write K" + std::to_string( i ) );
			}
			if ( addr == self->prog_->epilogue_at && !self->ext_out_done_ )
			{
				self->ext_out_done_ = true;
				state& out = *self->cur_->s;
				for ( int i = 0; i < 32; ++i )
				{
					uint8_t z[ 64 ] = {};
					if ( uc_reg_read( uc, UC_X86_REG_ZMM0 + i, z ) != UC_ERR_OK ) self->ext_err( "uc_reg_read ZMM" + std::to_string( i ) );
					if ( i < 16 ) std::memcpy( out.zmmh[ i ], z + 32, 32 );
					else std::memcpy( out.zmmx[ i - 16 ], z, 64 );
				}
				for ( int i = 0; i < 8; ++i )
					if ( uc_reg_read( uc, UC_X86_REG_K0 + i, &out.k[ i ] ) != UC_ERR_OK ) self->ext_err( "uc_reg_read K" + std::to_string( i ) );
			}
		}
		void ext_err( const std::string& e ) { if ( cur_ && cur_->err.empty() ) cur_->err = e; }
		bool pending_epilogue_ = false, ext_in_done_ = false, ext_out_done_ = false;
		uc_engine* uc_ = nullptr;
		const state* in_ = nullptr;
	public:
		std::vector<uc_x86_cpuid> cpuid;
		int strict = 0;
		uint64_t xcr0 = 0;
		uint64_t cr0 = 0;
		bool ext_regs = false;   // move ZMM0-31 / K0-7 (state::zmmh/zmmx/k) through code hooks
	private:
		int model_;
		uint32_t quirks_;
		const program* prog_ = nullptr;
		result* cur_ = nullptr;
	};
}
