// emu-alltest engines (plan step 1.9): one self-generated thunk, byte-identical in two engines.
//   * host CPU  - hardware reference; only snippets generated by this program ever run natively
//   * Unicorn   - our QEMU 7.2.22 branch (UC_CPU_X86_MAX: every feature the translator implements)
// The thunk loads the full input state (GPRs, RFLAGS, FXSAVE image = x87 + MXCSR + XMM, YMM upper
// halves, a test stack and a 64 KiB operand region), runs the snippet, and saves the full output
// state (+ FNSTENV for the full x87 tag word). Faults are recorded (native: vectored exception
// handler; Unicorn: UC_HOOK_INTR / UC_HOOK_INSN_INVALID / unmapped-memory hooks) and both engines
// resume at the same save-state epilogue.
// Derived from the plan-1.6 backport harness (tag backport-tests-1.6).
#pragma once
#include <unicorn/unicorn.h>
#include <keystone/keystone.h>
#include <windows.h>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

namespace at
{
	// ── fixed layout (identical in both engines) ─────────────────────────────────────────────
	constexpr uint64_t CODE = 0x30000000, CODE_SIZE = 0x10000;
	constexpr uint64_t DATA = 0x30010000, DATA_SIZE = 0x10000;     // state blocks, stacks
	constexpr uint64_t MEM = 0x30020000, MEM_SIZE = 0x10000;       // operand memory (compared)
	constexpr uint64_t IN_BLK = DATA + 0x0000, OUT_BLK = DATA + 0x1000, HOST = DATA + 0x2000;
	constexpr uint64_t STACK_LO = DATA + 0x3000, STACK_TOP = DATA + 0x3F00;
	constexpr uint64_t EPI_STACK = DATA + 0x6000;
	constexpr uint64_t MEM_PTR = MEM + 0x8000;                       // rsi / r14: [rsi], [rsi+rcx]
	constexpr uint64_t MEM_DST = MEM + 0x9000;                       // rdi: string destination
	// case option "cpl=3" (Unicorn only; the host always runs at CPL3): a Windows x64 GDT
	// (10h code64 DPL0, 18h data DPL0, 23h code32 DPL3 = compatibility mode, 2Bh data DPL3,
	// 33h code64 DPL3), a CPL0 stub that IRETQs to the thunk with CS = 33h / SS = 2Bh, and a
	// compatibility-mode gate (push 33h; push epilogue; retf) used to resume after a fault
	// taken in compatibility mode. Unicorn-only page, never compared.
	constexpr uint64_t SYS_PAGE = 0x30040000, SYS_SIZE = 0x1000;
	constexpr uint64_t SYS_GDT = SYS_PAGE, SYS_STUB = SYS_PAGE + 0x800, SYS_GATE = SYS_PAGE + 0x900;
	constexpr uint16_t SEL_CODE32_R3 = 0x23, SEL_DATA_R3 = 0x2B, SEL_CODE64_R3 = 0x33;
	// U850: branch layout (sweep forms that transfer control, program::ctl). The CODE region is filled
	// with HLT (F4h) in both engines: CPL3 HLT is #GP(0) with RIP = its own address (fault-like), so a
	// transfer that leaves the snippet stops at its target and both engines report that address. LAND
	// is the target the sweep gives indirect transfers and returns (CALL/JMP r/m, RET, RETF, far CALL/
	// JMP m16:xx); the snippet sits between two HLT pads (CTL_PAD each), so a rel8 target lands in a pad
	// and a rel32 target beyond the program in the fill.
	constexpr uint64_t LAND = CODE + 0x8000;
	constexpr size_t CTL_PAD = 0x100;
	constexpr uint8_t CTL_FILL = 0xF4;

	constexpr uint64_t S_GPR = 0x000, S_RFLAGS = 0x080, S_FX = 0x100, S_YMMH = 0x300, S_ENV = 0x400;

	enum reg { RAX, RCX, RDX, RBX, RSP, RBP, RSI, RDI, R8, R9, R10, R11, R12, R13, R14, R15 };
	inline const char* reg_name( int i )
	{
		static const char* n[] = { "rax","rcx","rdx","rbx","rsp","rbp","rsi","rdi","r8","r9","r10","r11","r12","r13","r14","r15" };
		return n[ i ];
	}

	struct state
	{
		uint64_t gpr[ 16 ];
		uint64_t rflags;
		uint8_t fx[ 512 ];
		uint8_t ymmh[ 16 ][ 16 ];
		uint8_t env[ 28 ];
		// AVX-512 state outside the thunk's XMM/YMM image: only the Unicorn engine moves it (code
		// hooks at the snippet's first instruction and at the epilogue, ext_regs = true); the host
		// CPU has no AVX-512, so the native engine leaves these zero
		uint8_t zmmh[ 16 ][ 32 ];   // ZMM0-15 bits 511:256
		uint8_t zmmx[ 16 ][ 64 ];   // ZMM16-31 bits 511:0
		uint64_t k[ 8 ];            // opmask K0-K7
		uint64_t egpr[ 16 ];        // Intel APX R16-R31 (U614: --apx; Unicorn only, like ZMM/K)
		uint8_t stack[ STACK_TOP - STACK_LO ];
		uint8_t mem[ MEM_SIZE ];

		uint16_t fcw() const { uint16_t v; std::memcpy( &v, fx + 0, 2 ); return v; }
		uint16_t fsw() const { uint16_t v; std::memcpy( &v, fx + 2, 2 ); return v; }
		uint8_t ftw_abridged() const { return fx[ 4 ]; }
		uint16_t ftw_full() const { uint16_t v; std::memcpy( &v, env + 8, 2 ); return v; }
		uint32_t mxcsr() const { uint32_t v; std::memcpy( &v, fx + 24, 4 ); return v; }
		const uint8_t* st( int i ) const { return fx + 32 + i * 16; }
		const uint8_t* xmm( int i ) const { return fx + 160 + i * 16; }
	};

	struct result
	{
		std::unique_ptr<state> s = std::make_unique<state>();
		bool ran = false;
		bool faulted = false;
		int vector = -1;            // x86 vector; Unicorn exact, native mapped from the NTSTATUS
		int64_t error_code = -1;    // U772: Unicorn's error code (UC_CTL_X86_EXCEPTION), -1 = none / native
		uint64_t fault_rip = 0;
		std::string err;
	};

	inline std::string hx( uint64_t v ) { char b[ 24 ]; std::snprintf( b, sizeof( b ), "0x%llX", ( unsigned long long ) v ); return b; }

	// ── assembling (self-generated code only) ───────────────────────────────────────────────
	// U545: Keystone never initialises MCAsmInfo::Radix (MCAsmInfo's constructor leaves it out;
	// ks_option can only set 16), so a fresh engine occasionally reads a plain immediate as hex
	// ("shrd rax, rcx, 26" -> imm8 26h): 8 of 160000 fresh engines under parallel load, which gave
	// both engines the same wrong instruction. Every engine is checked with "mov eax, 10" (B8 0A 00
	// 00 00 only in radix 10) and reopened until it reads decimal.
	inline ks_engine* ks_open_decimal()
	{
		static const unsigned char want[] = { 0xB8, 0x0A, 0x00, 0x00, 0x00 };
		for ( int tries = 0; tries < 64; ++tries )
		{
			ks_engine* ks = nullptr;
			if ( ks_open( KS_ARCH_X86, KS_MODE_64, &ks ) != KS_ERR_OK ) return nullptr;
			unsigned char* enc = nullptr;
			size_t size = 0, count = 0;
			bool decimal = ks_asm( ks, "mov eax, 10", 0, &enc, &size, &count ) == KS_ERR_OK && size == sizeof( want ) &&
						   !std::memcmp( enc, want, sizeof( want ) );
			if ( enc ) ks_free( enc );
			if ( decimal ) return ks;
			ks_close( ks );
		}
		return nullptr;
	}

	inline std::vector<uint8_t> assemble( const std::string& text, uint64_t addr, std::string* err = nullptr )
	{
		ks_engine* ks = ks_open_decimal();
		std::vector<uint8_t> out;
		if ( !ks ) { if ( err ) *err = "ks_open (no engine with decimal immediates)"; return out; }
		unsigned char* enc = nullptr;
		size_t size = 0, count = 0;
		if ( ks_asm( ks, text.c_str(), addr, &enc, &size, &count ) != KS_ERR_OK ) { if ( err ) *err = ks_strerror( ks_errno( ks ) ); }
		else out.assign( enc, enc + size );
		if ( enc ) ks_free( enc );
		ks_close( ks );
		return out;
	}

	// Keystone encodes an absolute [imm] operand as RIP-relative in 64-bit mode, so all state
	// accesses go through rax = DATA.
	inline std::string at( uint64_t addr ) { return "[rax + " + hx( addr - DATA ) + "]"; }

	inline std::string prologue_text()
	{
		std::string s = "mov rax, " + hx( DATA ) + "\n";
		const char* hs[] = { "rbx", "rbp", "rdi", "rsi", "r12", "r13", "r14", "r15" };
		for ( int i = 0; i < 8; ++i ) s += "mov qword ptr " + at( HOST + i * 8 ) + ", " + hs[ i ] + "\n";
		s += "mov qword ptr " + at( HOST + 0x40 ) + ", rsp\n";
		s += "fnstcw word ptr " + at( HOST + 0x48 ) + "\nstmxcsr dword ptr " + at( HOST + 0x4C ) + "\n";
		for ( int i = 6; i < 16; ++i ) s += "movdqu xmmword ptr " + at( HOST + 0x80 + ( i - 6 ) * 16 ) + ", xmm" + std::to_string( i ) + "\n";
		s += "mov rsp, qword ptr " + at( IN_BLK + S_GPR + RSP * 8 ) + "\n";
		s += "fxrstor64 " + at( IN_BLK + S_FX ) + "\n";
		for ( int i = 0; i < 16; ++i )
			s += "vinserti128 ymm" + std::to_string( i ) + ", ymm" + std::to_string( i ) + ", xmmword ptr " + at( IN_BLK + S_YMMH + i * 16 ) + ", 1\n";
		s += "push qword ptr " + at( IN_BLK + S_RFLAGS ) + "\npopfq\n";
		for ( int i = 1; i < 16; ++i )
			if ( i != RSP ) s += std::string( "mov " ) + reg_name( i ) + ", qword ptr " + at( IN_BLK + S_GPR + i * 8 ) + "\n";
		s += "mov rax, qword ptr " + at( IN_BLK + S_GPR + RAX * 8 ) + "\n";
		return s;
	}

	inline std::string epilogue_text()   // follows the raw "mov [moffs64], rax"
	{
		std::string s = "mov rax, " + hx( DATA ) + "\n";
		for ( int i = 1; i < 16; ++i ) s += "mov qword ptr " + at( OUT_BLK + S_GPR + i * 8 ) + ", " + reg_name( i ) + "\n";
		s += "mov rsp, " + hx( EPI_STACK ) + "\npushfq\npop qword ptr " + at( OUT_BLK + S_RFLAGS ) + "\npush 0x202\npopfq\n";
		s += "fxsave64 " + at( OUT_BLK + S_FX ) + "\n";
		for ( int i = 0; i < 16; ++i )
			s += "vextracti128 xmmword ptr " + at( OUT_BLK + S_YMMH + i * 16 ) + ", ymm" + std::to_string( i ) + ", 1\n";
		s += "fnstenv " + at( OUT_BLK + S_ENV ) + "\nfninit\n";
		s += "fldcw word ptr " + at( HOST + 0x48 ) + "\nldmxcsr dword ptr " + at( HOST + 0x4C ) + "\n";
		const char* hs[] = { "rbx", "rbp", "rdi", "rsi", "r12", "r13", "r14", "r15" };
		for ( int i = 0; i < 8; ++i ) s += std::string( "mov " ) + hs[ i ] + ", qword ptr " + at( HOST + i * 8 ) + "\n";
		for ( int i = 6; i < 16; ++i ) s += "movdqu xmm" + std::to_string( i ) + ", xmmword ptr " + at( HOST + 0x80 + ( i - 6 ) * 16 ) + "\n";
		s += "mov rsp, qword ptr " + at( HOST + 0x40 ) + "\nvzeroupper\nret\n";
		return s;
	}

	struct program
	{
		std::vector<uint8_t> code;
		uint64_t snippet_begin = 0, snippet_end = 0, epilogue_at = 0, ret_at = 0;
		// U850: branch layout: prologue, JMP over a HLT pad, snippet, JMP over a HLT pad, epilogue;
		// the rest of CODE is HLT. A fault anywhere but the prologue [CODE, prologue_end) and the
		// epilogue [epilogue_at, CODE + code.size()) belongs to the snippet (see in_trap_range).
		bool ctl = false;
		uint64_t prologue_end = 0;
		uint8_t fill = 0xCC;       // the CODE bytes outside the program (native; Unicorn: 0 unless ctl)
		// a fault at this RIP is the snippet's: resume at the epilogue
		bool in_trap_range( uint64_t rip ) const
		{
			if ( !ctl ) return rip >= snippet_begin && rip < snippet_end;
			if ( rip >= CODE && rip < prologue_end ) return false;
			if ( rip >= epilogue_at && rip < CODE + code.size() ) return false;
			if ( rip >= SYS_PAGE && rip < SYS_PAGE + SYS_SIZE ) return false;   // Unicorn's CPL0 stub / gate
			return true;
		}
	};

	inline std::vector<uint8_t> epilogue_bytes( uint64_t epi_addr, std::string* err )
	{
		std::vector<uint8_t> epi = { 0x48, 0xA3 };   // mov [moffs64], rax  - a true absolute store of the guest rax
		for ( int i = 0; i < 8; ++i ) epi.push_back( uint8_t( ( OUT_BLK + S_GPR ) >> ( 8 * i ) ) );
		std::vector<uint8_t> rest = assemble( epilogue_text(), epi_addr + epi.size(), err );
		if ( rest.empty() ) return {};
		epi.insert( epi.end(), rest.begin(), rest.end() );
		return epi;
	}

	inline void put_jmp32( std::vector<uint8_t>& code, size_t over )   // E9 rel32: skip 'over' bytes
	{
		code.push_back( 0xE9 );
		for ( int i = 0; i < 4; ++i ) code.push_back( uint8_t( uint32_t( over ) >> ( 8 * i ) ) );
	}

	// The prologue is fixed; the epilogue only depends on where it starts. Both are assembled
	// once per snippet length and cached. ctl (U850): the branch layout of program::ctl.
	inline program build( const std::vector<uint8_t>& snippet, std::string* err, bool ctl = false )
	{
		static std::vector<uint8_t> pro = assemble( prologue_text(), CODE, err );
		// U759: snippets up to 255 bytes (the CPL0 CET sequences of cases_cet2.txt set up a GDT,
		// CR4.CET and the CET MSRs themselves)
		static std::vector<std::vector<uint8_t>> epi_cache( 256 ), epi_cache_ctl( 256 );
		program p;
		if ( pro.empty() || snippet.size() >= epi_cache.size() ) return p;
		const size_t jmp = ctl ? 5 : 0, pad = ctl ? CTL_PAD : 0;
		uint64_t snip_addr = CODE + pro.size() + jmp + pad;
		uint64_t epi_addr = snip_addr + snippet.size() + jmp + pad;
		auto& epi = ( ctl ? epi_cache_ctl : epi_cache )[ snippet.size() ];
		if ( epi.empty() )
		{
			epi = epilogue_bytes( epi_addr, err );
			if ( epi.empty() ) return p;
		}
		p.code = pro;
		if ( ctl )
		{
			put_jmp32( p.code, pad );
			p.code.insert( p.code.end(), pad, CTL_FILL );
		}
		p.code.insert( p.code.end(), snippet.begin(), snippet.end() );
		if ( ctl )
		{
			put_jmp32( p.code, pad );
			p.code.insert( p.code.end(), pad, CTL_FILL );
		}
		p.code.insert( p.code.end(), epi.begin(), epi.end() );
		p.snippet_begin = snip_addr;
		p.snippet_end = snip_addr + snippet.size();
		p.epilogue_at = epi_addr;
		p.ret_at = CODE + p.code.size() - 1;
		p.ctl = ctl;
		p.prologue_end = CODE + pro.size() + jmp;
		if ( ctl ) p.fill = CTL_FILL;
		return p;
	}

	inline void write_blocks( uint8_t* data, uint8_t* mem, const state& s )
	{
		uint8_t* in = data + ( IN_BLK - DATA );
		std::memset( in, 0, 0x1000 );
		std::memcpy( in + S_GPR, s.gpr, sizeof( s.gpr ) );
		std::memcpy( in + S_RFLAGS, &s.rflags, 8 );
		std::memcpy( in + S_FX, s.fx, 512 );
		std::memcpy( in + S_YMMH, s.ymmh, sizeof( s.ymmh ) );
		std::memcpy( data + ( STACK_LO - DATA ), s.stack, sizeof( s.stack ) );
		std::memcpy( mem, s.mem, MEM_SIZE );
	}

	inline void read_blocks( const uint8_t* data, const uint8_t* mem, state& s )
	{
		const uint8_t* out = data + ( OUT_BLK - DATA );
		std::memcpy( s.gpr, out + S_GPR, sizeof( s.gpr ) );
		std::memcpy( &s.rflags, out + S_RFLAGS, 8 );
		std::memcpy( s.fx, out + S_FX, 512 );
		std::memcpy( s.ymmh, out + S_YMMH, sizeof( s.ymmh ) );
		std::memcpy( s.env, out + S_ENV, sizeof( s.env ) );
		std::memcpy( s.stack, data + ( STACK_LO - DATA ), sizeof( s.stack ) );
		std::memcpy( s.mem, mem, MEM_SIZE );
	}

	// ── host CPU (self-generated code only) ─────────────────────────────────────────────────
	class native_engine
	{
	public:
		bool open( std::string& err )
		{
			code_ = ( uint8_t* ) VirtualAlloc( ( void* ) CODE, CODE_SIZE, MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE );
			data_ = ( uint8_t* ) VirtualAlloc( ( void* ) DATA, DATA_SIZE, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE );
			mem_ = ( uint8_t* ) VirtualAlloc( ( void* ) MEM, MEM_SIZE, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE );
			if ( code_ != ( void* ) CODE || data_ != ( void* ) DATA || mem_ != ( void* ) MEM ) { err = "VirtualAlloc at the fixed addresses failed"; return false; }
			veh_ = AddVectoredExceptionHandler( 1, veh );
			return true;
		}
		~native_engine()
		{
			if ( veh_ ) RemoveVectoredExceptionHandler( veh_ );
			for ( void* p : { ( void* ) code_, ( void* ) data_, ( void* ) mem_ } ) if ( p ) VirtualFree( p, 0, MEM_RELEASE );
		}
		void run( const program& p, const state& in, result& r )
		{
			std::memset( code_, p.fill, CODE_SIZE );
			std::memcpy( code_, p.code.data(), p.code.size() );
			FlushInstructionCache( GetCurrentProcess(), code_, CODE_SIZE );
			std::memset( data_, 0, DATA_SIZE );
			write_blocks( data_, mem_, in );
			g().lo = p.snippet_begin; g().hi = p.snippet_end; g().resume = p.epilogue_at;
			g().faulted = false; g().code = 0; g().rip = 0;
			// U850: a branch-layout snippet may fault outside its own bytes (at its target: the HLT
			// fill, or an unmapped address below 64 KiB); only this thread, only while it runs
			g().prog = &p; g().tid = GetCurrentThreadId(); g().active = true;
			( ( void( * )() ) code_ )();
			g().active = false; g().prog = nullptr;
			r.ran = true;
			r.faulted = g().faulted;
			r.vector = g().faulted ? vector_of( g().code, g().info0, g().info1 ) : -1;
			// Windows reports #MF and #XM with the same STATUS_FLOAT_* codes: an x87 opcode
			// (D8-DF, or FWAIT 9B) at the faulting RIP is #MF (16), anything else #XM (19)
			if ( r.vector == 16 && g().rip >= ( uint64_t ) code_ && g().rip < ( uint64_t ) code_ + CODE_SIZE )
			{
				const uint8_t* q = ( const uint8_t* ) g().rip;
				while ( *q == 0x66 || *q == 0x67 || *q == 0xF2 || *q == 0xF3 || ( *q & 0xF0 ) == 0x40 ) ++q;
				if ( !( ( *q >= 0xD8 && *q <= 0xDF ) || *q == 0x9B ) ) r.vector = 19;
			}
			r.fault_rip = g().rip;
			read_blocks( data_, mem_, *r.s );
		}
	private:
		struct globals { uint64_t lo, hi, resume, rip, info0, info1; DWORD code; bool faulted; const program* prog; DWORD tid; bool active; };
		static globals& g() { static globals x{}; return x; }
		static LONG CALLBACK veh( EXCEPTION_POINTERS* ep )
		{
			uint64_t rip = ep->ContextRecord->Rip;
			if ( g().active && g().prog && g().prog->ctl )
			{
				// U850: branch layout - everything but the prologue / epilogue, on the running thread
				if ( GetCurrentThreadId() != g().tid || !g().prog->in_trap_range( rip ) ) return EXCEPTION_CONTINUE_SEARCH;
			}
			else if ( rip < g().lo || rip >= g().hi ) return EXCEPTION_CONTINUE_SEARCH;
			g().faulted = true;
			g().code = ep->ExceptionRecord->ExceptionCode;
			g().info0 = ep->ExceptionRecord->NumberParameters >= 1 ? ep->ExceptionRecord->ExceptionInformation[ 0 ] : 0;
			g().info1 = ep->ExceptionRecord->NumberParameters >= 2 ? ep->ExceptionRecord->ExceptionInformation[ 1 ] : 0;
			g().rip = rip;
			// a trap (single step) leaves TF set in the context: clear it before resuming
			ep->ContextRecord->EFlags &= ~0x100u;
			ep->ContextRecord->Rip = g().resume;
			// a snippet that switched to compatibility mode (far transfer to CS = 23h) faulted
			// there: the epilogue is 64-bit code, so resume with the 64-bit user CS (33h)
			if ( ep->ContextRecord->SegCs == SEL_CODE32_R3 ) ep->ContextRecord->SegCs = SEL_CODE64_R3;
			return EXCEPTION_CONTINUE_EXECUTION;
		}
		static int vector_of( DWORD code, uint64_t info0, uint64_t info1 )
		{
			switch ( code )
			{
				case STATUS_INTEGER_DIVIDE_BY_ZERO: case STATUS_INTEGER_OVERFLOW: return 0;
				case STATUS_SINGLE_STEP: return 1;
				case STATUS_BREAKPOINT: return 3;
				// a trap taken in compatibility mode (CS = 23h, cpl=3 cases) is reported with the
				// WOW64 codes STATUS_WX86_SINGLE_STEP / STATUS_WX86_BREAKPOINT
				case 0x4000001E: return 1;
				case 0x4000001F: return 3;
				case STATUS_ILLEGAL_INSTRUCTION: return 6;
				case STATUS_PRIVILEGED_INSTRUCTION: return 13;
				// #GP reports address -1; U773: a #SS (non-canonical stack reference) reports
				// ExceptionInformation[0] = 3 and address 0 (a #PF: 0 read, 1 write, 8 execute and the
				// address; Windows 10 19044 on the i5-13600K, cases_fix4.txt)
				case STATUS_ACCESS_VIOLATION: return info1 == ~0ull ? 13 : info0 == 3 ? 12 : 14;
				case STATUS_DATATYPE_MISALIGNMENT: return 17;
				case STATUS_FLOAT_MULTIPLE_FAULTS: case STATUS_FLOAT_MULTIPLE_TRAPS: return 19;
				case STATUS_FLOAT_INVALID_OPERATION: case STATUS_FLOAT_DIVIDE_BY_ZERO: case STATUS_FLOAT_OVERFLOW:
				case STATUS_FLOAT_UNDERFLOW: case STATUS_FLOAT_INEXACT_RESULT: case STATUS_FLOAT_DENORMAL_OPERAND:
				case STATUS_FLOAT_STACK_CHECK: return 16;
				default: return 100 + int( code & 0xFF );
			}
		}
		uint8_t* code_ = nullptr; uint8_t* data_ = nullptr; uint8_t* mem_ = nullptr;
		PVOID veh_ = nullptr;
	};

	// ── Unicorn ─────────────────────────────────────────────────────────────────────────────
	// U539: Unicorn implements the Intel SDM only (no UC_CTL_X86_HW_QUIRKS, no --quirks). Where
	// the host i5-13600K deviates, the hardware cases are tagged (docs\quirks.md, at_cases.hpp).

	class unicorn_engine
	{
	public:
		explicit unicorn_engine( int model ) : model_( model ) {}
		// a fresh engine with the CPU model, the opt-ins, the CPUID profile / strict setting and the
		// XCR0 / CR0 writes (0 = not written: Unicorn's reset value) applied, nothing mapped yet
		bool open_configured( std::string& err )
		{
			close();
			uc_err e = uc_open( UC_ARCH_X86, UC_MODE_64, &uc_ );
			if ( e ) { err = std::string( "uc_open: " ) + uc_strerror( e ); return false; }
			uc_ctl_set_cpu_model( uc_, model_ );
			// AVX-512 opt-in (emu-alltest --avx512): only before the engine is initialised
			if ( avx512 && uc_ctl_set_x86_avx512( uc_, avx512 ) != UC_ERR_OK ) { err = "uc_ctl_set_x86_avx512 failed"; return false; }
			// AMX opt-in (emu-alltest --amx, UC_CTL_X86_AMX = UC_X86_AMX_ALL): same rule
			if ( amx && uc_ctl_set_x86_amx( uc_, amx ) != UC_ERR_OK ) { err = "uc_ctl_set_x86_amx failed"; return false; }
			// AVX10 opt-in (emu-alltest --avx10 N, UC_CTL_X86_AVX10 = N): same rule
			if ( avx10 && uc_ctl_set_x86_avx10( uc_, avx10 ) != UC_ERR_OK ) { err = "uc_ctl_set_x86_avx10 failed"; return false; }
			// APX opt-in (emu-alltest --apx, UC_CTL_X86_APX = UC_X86_APX_F, U610): same rule
			if ( apx && uc_ctl_set_x86_apx( uc_, apx ) != UC_ERR_OK ) { err = "uc_ctl_set_x86_apx failed"; return false; }
			// U835 (D8): RDRAND/RDSEED source, --seeded (default, deterministic) or --HostSeed
			if ( uc_ctl_set_x86_rdrand( uc_, rdrand, rdrand_seed ) != UC_ERR_OK ) { err = "uc_ctl_set_x86_rdrand failed"; return false; }
			// optional CPUID profile / strict-#UD / XCR0 (emu-alltest --cpuid/--strict/--xcr0)
			if ( !cpuid.empty() ) uc_ctl_set_x86_cpuid( uc_, cpuid.data(), cpuid.size() );
			// U435: -1 leaves Unicorn's default (strict while a profile is installed)
			if ( strict >= 0 ) uc_ctl_set_x86_cpuid_strict( uc_, strict );
			if ( xcr0 ) uc_reg_write( uc_, UC_X86_REG_XCR0, &xcr0 );
			if ( cr0 ) uc_reg_write( uc_, UC_X86_REG_CR0, &cr0 );
			return true;
		}
		// U540: the XCR0 / CR0 an engine with this configuration starts from (printed at the start
		// of a --cases run: the effective machine state, reset values included)
		bool probe( uint64_t& xcr0_out, uint64_t& cr0_out, std::string& err )
		{
			bool ok = open_configured( err );
			if ( ok && ( uc_reg_read( uc_, UC_X86_REG_XCR0, &xcr0_out ) != UC_ERR_OK || uc_reg_read( uc_, UC_X86_REG_CR0, &cr0_out ) != UC_ERR_OK ) )
			{
				err = "uc_reg_read XCR0/CR0 failed";
				ok = false;
			}
			close();
			return ok;
		}
		// one engine per form (fresh translation cache), reused across that form's iterations
		bool load( const program& p, std::string& err )
		{
			if ( !open_configured( err ) ) return false;
			uc_mem_map( uc_, CODE, CODE_SIZE, UC_PROT_ALL );
			uc_mem_map( uc_, DATA, DATA_SIZE, UC_PROT_READ | UC_PROT_WRITE );
			uc_mem_map( uc_, MEM, MEM_SIZE, UC_PROT_READ | UC_PROT_WRITE );
			if ( p.ctl )   // U850: the HLT fill of the branch layout, as natively
			{
				std::vector<uint8_t> fill( CODE_SIZE, p.fill );
				uc_mem_write( uc_, CODE, fill.data(), fill.size() );
			}
			uc_mem_write( uc_, CODE, p.code.data(), p.code.size() );
			if ( cpl3 )
			{
				// Windows x64 GDT layout; flat descriptors (64-bit code: L = 1, D = 0)
				const uint64_t gdt[ 7 ] = { 0, 0, 0x00209B0000000000ull, 0x00CF93000000FFFFull, 0x00CFFB000000FFFFull,
											 0x00CFF3000000FFFFull, 0x0020FB0000000000ull };
				uc_mem_map( uc_, SYS_PAGE, SYS_SIZE, UC_PROT_ALL );
				uc_mem_write( uc_, SYS_GDT, gdt, sizeof( gdt ) );
				uc_x86_mmr gdtr = { 0, SYS_GDT, sizeof( gdt ) - 1, 0 };
				uc_reg_write( uc_, UC_X86_REG_GDTR, &gdtr );
				// CPL0 stub: mov rax, rsp; push 2Bh; push rax; push 202h; push 33h; push CODE; iretq
				const uint8_t stub[] = { 0x48, 0x89, 0xE0, 0x6A, SEL_DATA_R3, 0x50, 0x68, 0x02, 0x02, 0x00, 0x00, 0x6A, SEL_CODE64_R3,
										 0x68, uint8_t( CODE ), uint8_t( CODE >> 8 ), uint8_t( CODE >> 16 ), uint8_t( CODE >> 24 ), 0x48, 0xCF };
				uc_mem_write( uc_, SYS_STUB, stub, sizeof( stub ) );
				// compatibility-mode gate (32-bit code): push 33h; push epilogue; retf
				const uint32_t epi = uint32_t( p.epilogue_at );
				const uint8_t gate[] = { 0x6A, SEL_CODE64_R3, 0x68, uint8_t( epi ), uint8_t( epi >> 8 ), uint8_t( epi >> 16 ), uint8_t( epi >> 24 ), 0xCB };
				uc_mem_write( uc_, SYS_GATE, gate, sizeof( gate ) );
				// IA32_EFER.SCE = 1 as under Windows (SYSCALL/SYSRET enabled)
				uc_x86_msr efer = { 0xC0000080, 0 };
				uc_reg_read( uc_, UC_X86_REG_MSR, &efer );
				efer.value |= 1;
				uc_reg_write( uc_, UC_X86_REG_MSR, &efer );
			}
			uc_hook h;
			uc_hook_add( uc_, &h, UC_HOOK_INTR, ( void* ) on_intr, this, 1, 0 );
			uc_hook_add( uc_, &h, UC_HOOK_INSN_INVALID, ( void* ) on_invalid, this, 1, 0 );
			uc_hook_add( uc_, &h, UC_HOOK_MEM_UNMAPPED, ( void* ) on_unmapped, this, 1, 0 );
			if ( ext_regs )
			{
				// ZMM0-31 / K0-7 in at the snippet's first instruction, out at the epilogue's first
				// instruction (the prologue's VEX loads zero ZMM bits 511:256, the epilogue's
				// VZEROUPPER would zero them again)
				uc_hook_add( uc_, &h, UC_HOOK_CODE, ( void* ) on_ext, this, p.snippet_begin, p.snippet_begin );
				if ( p.epilogue_at != p.snippet_begin )
					uc_hook_add( uc_, &h, UC_HOOK_CODE, ( void* ) on_ext, this, p.epilogue_at, p.epilogue_at );
			}
			prog_ = &p;
			return true;
		}
		~unicorn_engine() { close(); }
		void run( const state& in, result& r )
		{
			std::vector<uint8_t> data( DATA_SIZE, 0 ), mem( MEM_SIZE );
			write_blocks( data.data(), mem.data(), in );
			uc_mem_write( uc_, DATA, data.data(), data.size() );
			uc_mem_write( uc_, MEM, mem.data(), mem.size() );
			uint64_t rsp = HOST + 0x800;
			uc_reg_write( uc_, UC_X86_REG_RSP, &rsp );
			cur_ = &r;
			in_ = &in;
			ext_in_done_ = ext_out_done_ = false;
			pending_epilogue_ = false;
			uc_err e = uc_emu_start( uc_, cpl3 ? SYS_STUB : CODE, prog_->ret_at, 0, 0 );
			if ( e && pending_epilogue_ )
			{
				// an unmapped access inside the snippet stopped the run (#PF): save the state at
				// the faulting instruction by running the epilogue, as the native VEH path does
				uint64_t fl = 0; uc_reg_read( uc_, UC_X86_REG_RFLAGS, &fl ); fl &= ~0x100ull; uc_reg_write( uc_, UC_X86_REG_RFLAGS, &fl );
				e = uc_emu_start( uc_, resume_target(), prog_->ret_at, 0, 0 );
			}
			if ( e ) r.err = std::string( "uc_emu_start: " ) + uc_strerror( e );
			uc_mem_read( uc_, DATA, data.data(), data.size() );
			uc_mem_read( uc_, MEM, mem.data(), mem.size() );
			read_blocks( data.data(), mem.data(), *r.s );
			r.ran = !e;
			if ( ext_regs && !ext_out_done_ && r.err.empty() ) r.err = "epilogue not reached: ZMM/K state not read";
			cur_ = nullptr;
			in_ = nullptr;
		}
	private:
		void close() { if ( uc_ ) uc_close( uc_ ); uc_ = nullptr; }
		void fault( uint64_t rip, int vec, int64_t ec = -1 )
		{
			if ( !cur_->faulted ) { cur_->faulted = true; cur_->vector = vec; cur_->fault_rip = rip; cur_->error_code = ec; }
		}
		// the epilogue, or in CPL3 mode with CS = 23h (a snippet in compatibility mode) the gate
		// that far-returns to the 64-bit epilogue
		uint64_t resume_target()
		{
			if ( cpl3 )
			{
				uint16_t cs = 0;
				uc_reg_read( uc_, UC_X86_REG_CS, &cs );
				if ( cs == SEL_CODE32_R3 ) return SYS_GATE;
			}
			return prog_->epilogue_at;
		}
		bool resume_if_in_snippet( uint64_t rip )
		{
			if ( !prog_->in_trap_range( rip ) ) return false;   // U850: the branch layout's wider range
			uint64_t to = resume_target();
			uc_reg_write( uc_, UC_X86_REG_RIP, &to );
			// clear TF so a single-step trap does not repeat inside the epilogue
			uint64_t fl = 0; uc_reg_read( uc_, UC_X86_REG_RFLAGS, &fl ); fl &= ~0x100ull; uc_reg_write( uc_, UC_X86_REG_RFLAGS, &fl );
			return true;
		}
		static void on_intr( uc_engine* uc, uint32_t intno, void* user )
		{
			auto* self = ( unicorn_engine* ) user;
			uint64_t rip = 0; uc_reg_read( uc, UC_X86_REG_RIP, &rip );
			// U772: the error code of the exception (UC_CTL_X86_EXCEPTION, U770), for "#GP(0)" etc.
			uc_x86_exception e{};
			int64_t ec = -1;
			if ( uc_ctl_get_x86_exception( uc, &e ) == UC_ERR_OK && e.vector == int( intno ) && e.has_error_code ) ec = e.error_code;
			self->fault( rip, int( intno ), ec );
			if ( !self->resume_if_in_snippet( rip ) ) uc_emu_stop( uc );
		}
		static bool on_invalid( uc_engine* uc, void* user )
		{
			auto* self = ( unicorn_engine* ) user;
			uint64_t rip = 0; uc_reg_read( uc, UC_X86_REG_RIP, &rip );
			self->fault( rip, 6 );
			return self->resume_if_in_snippet( rip );
		}
		static bool on_unmapped( uc_engine* uc, uc_mem_type, uint64_t, int, int64_t, void* user )
		{
			// an access outside our regions: the host sees an access violation (#PF) there too
			auto* self = ( unicorn_engine* ) user;
			uint64_t rip = 0; uc_reg_read( uc, UC_X86_REG_RIP, &rip );
			self->fault( rip, 14 );
			if ( self->prog_->in_trap_range( rip ) ) self->pending_epilogue_ = true;   // U850: branch layout too
			return false;
		}
		static void on_ext( uc_engine* uc, uint64_t addr, uint32_t, void* user )
		{
			auto* self = ( unicorn_engine* ) user;
			if ( !self->cur_ || !self->in_ ) return;
			if ( addr == self->prog_->snippet_begin && !self->ext_in_done_ )
			{
				self->ext_in_done_ = true;
				const state& in = *self->in_;
				for ( int i = 0; i < 32; ++i )
				{
					uint8_t z[ 64 ];
					if ( i < 16 )
					{
						std::memcpy( z, in.xmm( i ), 16 );
						std::memcpy( z + 16, in.ymmh[ i ], 16 );
						std::memcpy( z + 32, in.zmmh[ i ], 32 );
					}
					else std::memcpy( z, in.zmmx[ i - 16 ], 64 );
					if ( uc_reg_write( uc, UC_X86_REG_ZMM0 + i, z ) != UC_ERR_OK ) self->ext_err( "uc_reg_write ZMM" + std::to_string( i ) );
				}
				for ( int i = 0; i < 8; ++i )
					if ( uc_reg_write( uc, UC_X86_REG_K0 + i, &in.k[ i ] ) != UC_ERR_OK ) self->ext_err( "uc_reg_write K" + std::to_string( i ) );
				// APX R16-R31 (--apx only: without APX the registers do not exist, UC_ERR_ARG)
				if ( self->apx )
					for ( int i = 0; i < 16; ++i )
						if ( uc_reg_write( uc, UC_X86_REG_R16 + i, &in.egpr[ i ] ) != UC_ERR_OK ) self->ext_err( "uc_reg_write R" + std::to_string( 16 + i ) );
			}
			if ( addr == self->prog_->epilogue_at && !self->ext_out_done_ )
			{
				self->ext_out_done_ = true;
				state& out = *self->cur_->s;
				for ( int i = 0; i < 32; ++i )
				{
					uint8_t z[ 64 ] = {};
					if ( uc_reg_read( uc, UC_X86_REG_ZMM0 + i, z ) != UC_ERR_OK ) self->ext_err( "uc_reg_read ZMM" + std::to_string( i ) );
					if ( i < 16 ) std::memcpy( out.zmmh[ i ], z + 32, 32 );
					else std::memcpy( out.zmmx[ i - 16 ], z, 64 );
				}
				for ( int i = 0; i < 8; ++i )
					if ( uc_reg_read( uc, UC_X86_REG_K0 + i, &out.k[ i ] ) != UC_ERR_OK ) self->ext_err( "uc_reg_read K" + std::to_string( i ) );
				if ( self->apx )
					for ( int i = 0; i < 16; ++i )
						if ( uc_reg_read( uc, UC_X86_REG_R16 + i, &out.egpr[ i ] ) != UC_ERR_OK ) self->ext_err( "uc_reg_read R" + std::to_string( 16 + i ) );
			}
		}
		void ext_err( const std::string& e ) { if ( cur_ && cur_->err.empty() ) cur_->err = e; }
		bool pending_epilogue_ = false, ext_in_done_ = false, ext_out_done_ = false;
		uc_engine* uc_ = nullptr;
		const state* in_ = nullptr;
	public:
		std::vector<uc_x86_cpuid> cpuid;
		int strict = -1;         // UC_CTL_X86_CPUID_STRICT: -1 = not written (U435), 0 / 1 = explicit
		uint64_t xcr0 = 0;
		uint64_t cr0 = 0;
		int avx512 = 0;          // UC_CTL_X86_AVX512 mask (0 = off, the default)
		int amx = 0;             // UC_CTL_X86_AMX mask (0 = off, the default)
		int avx10 = 0;           // UC_CTL_X86_AVX10 version (0 = off, the default)
		int apx = 0;             // UC_CTL_X86_APX (0 = off, the default; UC_X86_APX_F = --apx)
		int rdrand = UC_X86_RDRAND_SEEDED;   // UC_CTL_X86_RDRAND (U835): --seeded (default) / --HostSeed
		uint64_t rdrand_seed = 0;            // the seeded model's seed (--rdrand-seed N)
		bool ext_regs = false;   // move ZMM0-31 / K0-7 (state::zmmh/zmmx/k) and, with apx, R16-R31 through code hooks
		bool cpl3 = false;       // case option cpl=3: run the thunk at CPL3 with the Windows GDT (SYS_PAGE)
	private:
		int model_;
		const program* prog_ = nullptr;
		result* cur_ = nullptr;
	};
}
