#!/usr/bin/env python3
"""Generate Emulator/data/cases_fixes.txt (hardware lines only, self-generated snippets).

U91: LOCK on the multi-byte NOP / hint space 0F 19..0F 1F. For every opcode: every /r,
register forms (mod = 3, rm = 0 and 7) and memory forms ([rsi], [rsi+8]); no prefix and
66 / F3 / F2, LOCK before and after the SIMD prefix; REX.B register and REX.W memory forms;
ENDBR64/ENDBR32 (F3 0F 1E FA/FB) and RDSSPD/RDSSPQ (F3 [REX.W] 0F 1E C8+r) with and without
LOCK. The i5-13600K has no MPX and no CLDEMOTE (cpuid_i5-13600k.txt: CPUID.7.0:EBX[14] = 0,
ECX[25] = 0) and runs with shadow stacks / IBT off for the process, so every form is a NOP
without LOCK and #UD with LOCK.

usage: gen_cases_fixes.py [OUT]   (default: Emulator/data/cases_fixes.txt next to this tree)
"""
import os
import sys

HEADER = """\
# Small decode fixes (ledger U91-U99), hardware lines only (no "=>"): every snippet runs natively
# on the host and in Unicorn. Generated by Emulator/tools/isa/gen_cases_fixes.py; do not edit by hand.
#   emu-alltest --cases Emulator\\data\\cases_fixes.txt --cpuid Emulator\\data\\cpuid_i5-13600k.txt --strict
# Expected: every line SAME (cases: {n}, differing: 0).
#
# --- U91: 0F 19..0F 1F (multi-byte NOP, MPX hint space 0F 1A/1B, CLDEMOTE space 0F 1C, CET space
# 0F 1E): a NOP without LOCK, #UD with LOCK (i5-13600K: no MPX, no CLDEMOTE, CET off)."""


def fmt(bs, extra=""):
    s = ".byte " + ", ".join("0x%02x" % b for b in bs)
    return s + (" | " + extra if extra else "")


def lines():
    out = []
    ops = [0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f]
    modrms = []
    for r in range(8):
        modrms.append((0xc0 | (r << 3) | 0, []))      # reg, rm = rax
        modrms.append((0xc0 | (r << 3) | 7, []))      # reg, rm = rdi
        modrms.append((0x00 | (r << 3) | 6, []))      # [rsi]
        modrms.append((0x40 | (r << 3) | 6, [0x08]))  # [rsi+8]
    for op in ops:
        out.append("# 0F %02X /r: no prefix, 66, F3, F2; LOCK first or after the SIMD prefix" % op)
        for pfx in ([], [0x66], [0xf3], [0xf2]):
            for m, tail in modrms:
                out.append(fmt(pfx + [0x0f, op, m] + tail))
                out.append(fmt([0xf0] + pfx + [0x0f, op, m] + tail))
                if pfx:
                    out.append(fmt(pfx + [0xf0, 0x0f, op, m] + tail))
    out.append("# REX.B register form (rm = r15) and REX.W memory form")
    for op in ops:
        for lock in ([], [0xf0]):
            out.append(fmt(lock + [0x49, 0x0f, op, 0xc7]))
            out.append(fmt(lock + [0x48, 0x0f, op, 0x06]))
    out.append("# ENDBR64 / ENDBR32 and RDSSPD / RDSSPQ (NOPs while CET is off), with and without LOCK")
    for lock in ([], [0xf0]):
        out.append(fmt(lock + [0xf3, 0x0f, 0x1e, 0xfa]))
        out.append(fmt(lock + [0xf3, 0x0f, 0x1e, 0xfb]))
        for r in range(8):
            out.append(fmt(lock + [0xf3, 0x0f, 0x1e, 0xc8 | r], "rax=0x1122334455667788"))
            out.append(fmt(lock + [0xf3, 0x48, 0x0f, 0x1e, 0xc8 | r], "rax=0x1122334455667788"))
        out.append(fmt(lock + [0xf3, 0x49, 0x0f, 0x1e, 0xcf], "r15=0x1122334455667788"))
    return out


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    dst = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "..", "data", "cases_fixes.txt")
    body = lines()
    n = sum(1 for x in body if not x.startswith("#"))
    with open(dst, "w", newline="\r\n", encoding="ascii") as f:
        f.write(HEADER.format(n=n) + "\n")
        f.write("\n".join(body) + "\n")
    print("wrote %s: %d cases" % (os.path.normpath(dst), n))


if __name__ == "__main__":
    main()
