#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_cases_x87_cmp.py -- hardware cases (ledger U861) for the x87 compare and classify
instructions under unmasked exceptions: FCOM/FCOMP/FCOMPP, FUCOM/FUCOMP/FUCOMPP, FCOMI/FCOMIP,
FUCOMI/FUCOMIP, FICOM/FICOMP, FTST and FXAM with stack underflow (#IS), denormal (#D) and
invalid-arithmetic (#IA) operands, each with FCW.IM/DM masked and unmasked.

What the SDM fixes for an unmasked exception (Vol1 8.5.1.1 #IS, 8.5.1.2 #IA, 8.5.2 #D): IE / SF /
DE are set, "the top-of-stack pointer (TOP) and source operands remain unchanged" (no pop of
FCOMP/FCOMPP/FUCOMP/FUCOMPP/FCOMIP/FUCOMIP/FICOMP), C1 = 0 for an underflow; FCOM/FUCOM and
FCOMI/FUCOMI set their condition codes / ZF PF CF "only if the exception is masked" for #IA
(Vol2A FCOM Table 3-23 note, FUCOM, FCOMI Operation). #IS and #D carry no condition-code rule
(the emulator writes them as the i5-13600K does: "unordered" for #IS, the comparison result for
#D; docs\\quirks.md "SDM undefined, our choice"). The i5-13600K deviates on #IA only: it writes
"unordered" there too (docs\\quirks.md "x87 compare unmasked #IA condition codes"), so those
cases carry that tag.

Only these self-generated snippets run natively:
  python gen_cases_x87_cmp.py > Emulator\\data\\cases_x87_cmp_exc.txt
  emu-alltest --cases Emulator\\data\\cases_x87_cmp_exc.txt --cpuid Emulator\\data\\cpuid_i5-13600k.txt
"""

import sys

ONE = "3FFF:8000000000000000"
TWO = "4000:8000000000000000"
NEG = "BFFF:C000000000000000"
ZERO = "0000:0000000000000000"
DEN = "0000:4000000000000000"       # denormal
NDEN = "8000:0000000000000001"      # negative denormal
PDEN = "0000:8000000000000001"      # pseudo-denormal
QNAN = "7FFF:C000000000000001"
SNAN = "7FFF:A000000000000000"
UNNORM = "4000:0000000000000001"    # unsupported
INF = "FFFF:8000000000000000"

KIND = {ONE: "num", TWO: "num", NEG: "num", ZERO: "num", INF: "num",
        DEN: "den", NDEN: "den", PDEN: "den", QNAN: "qnan", SNAN: "snan", UNNORM: "bad", None: "empty"}

# memory operands (little-endian bytes) and their class
M32 = {"one": ("0000803F", "num"), "den": ("01000000", "den"), "snan": ("0100A07F", "snan"),
       "qnan": ("0100C07F", "qnan")}
M64 = {"one": ("000000000000F03F", "num"), "den": ("0100000000000000", "den"),
       "snan": ("010000000000F47F", "snan"), "qnan": ("010000000000F87F", "qnan")}
I16 = {"one": ("0100", "num"), "neg": ("FEFF", "num")}
I32 = {"one": ("01000000", "num"), "neg": ("FEFFFFFF", "num")}

FCWS = (0x037F, 0x037E, 0x037D, 0x037C)    # all masked, IM = 0, DM = 0, IM = DM = 0
FSW = 0x0300                               # C1 = 1, C0 = 1 before (C3 C2 C0 = 001, not 111)
FSW_FCOMI = 0x0100                         # C0 = 1 only: FCOMI's C1 is a separate deviation
RFLAGS = 0xA93                             # OF SF AF PF CF set before FCOMI (ZF PF CF = 011)

# family: "cc" FCOM/FUCOM-like (#IA keeps CC when unmasked), "eflags" FCOMI-like,
# "unord" FICOM/FTST (no IM rule), "fxam" (no exceptions)
REG2 = [("fcom st(1)", "cc", False), ("fcomp st(1)", "cc", False), ("fcompp", "cc", False),
        ("fucom st(1)", "cc", True), ("fucomp st(1)", "cc", True), ("fucompp", "cc", True),
        ("fcomi st(0), st(1)", "eflags", False), ("fcomip st(0), st(1)", "eflags", False),
        ("fucomi st(0), st(1)", "eflags", True), ("fucomip st(0), st(1)", "eflags", True)]
MEMF = [("fcom dword ptr [rsi]", M32), ("fcomp dword ptr [rsi]", M32),
        ("fcom qword ptr [rsi]", M64), ("fcomp qword ptr [rsi]", M64)]
MEMI = [("ficom word ptr [rsi]", I16), ("ficomp word ptr [rsi]", I16),
        ("ficom dword ptr [rsi]", I32), ("ficomp dword ptr [rsi]", I32)]

REG_PAIRS = [(None, ONE), (ONE, None), (None, None), (DEN, ONE), (ONE, DEN), (NDEN, NEG),
             (PDEN, TWO), (DEN, SNAN), (SNAN, DEN), (QNAN, DEN), (DEN, QNAN), (SNAN, ONE),
             (ONE, QNAN), (QNAN, QNAN), (UNNORM, ONE), (ZERO, DEN), (INF, DEN), (ONE, TWO)]
ST0_ONLY = [None, ONE, NEG, ZERO, DEN, NDEN, PDEN, QNAN, SNAN, UNNORM, INF]

DEV = " # known deviation: x87 compare unmasked #IA condition codes"


def raises_ia(k0, k1, unordered_ok):
    """#IA of FCOM/FUCOM/FCOMI/FUCOMI (no stack fault): unsupported or SNaN operand, or a
    QNaN for the ordered compares"""
    ks = (k0, k1)
    if "bad" in ks or "snan" in ks:
        return True
    return "qnan" in ks and not unordered_ok


def state(st0, st1):
    s = []
    if st0 is not None:
        s.append("st0=%s" % st0)
    if st1 is not None:
        s.append("st1=%s" % st1)
    return " ".join(s)


def main():
    out = sys.stdout
    out.write("# x87 compares / FTST / FXAM with unmasked #IS / #D / #IA (ledger U861), hardware cases\n")
    out.write("# generated by Emulator\\tools\\isa\\gen_cases_x87_cmp.py (regenerate, do not edit); FSW preset\n")
    out.write("# %04Xh (C1 = C0 = 1; FCOMI family %04Xh: the SDM sets its C1 to 0, the i5-13600K keeps it,\n"
              % (FSW, FSW_FCOMI))
    out.write("# docs\\quirks.md \"FCOMI/FUCOMI C1\", covered by cases_quirks.txt), FCOMI RFLAGS preset %Xh;\n"
              % RFLAGS)
    out.write("# FCW 037F/037E/037D/037C = masked / IM = 0 /\n")
    out.write("# DM = 0 / IM = DM = 0. Cases where the i5-13600K writes \"unordered\" on an unmasked #IA\n")
    out.write("# (the SDM keeps the flags) are tagged (docs\\quirks.md).\n")
    n = 0
    for asm, fam, unord in REG2:
        out.write("# %s\n" % asm)
        for st0, st1 in REG_PAIRS:
            for fcw in FCWS:
                k0, k1 = KIND[st0], KIND[st1]
                extra = " rflags=0x%X" % RFLAGS if fam == "eflags" else ""
                fsw = FSW_FCOMI if fam == "eflags" else FSW
                line = "%s | fcw=0x%04X fsw=0x%04X%s %s" % (asm, fcw, fsw, extra, state(st0, st1))
                stack = "empty" in (k0, k1)
                if not stack and raises_ia(k0, k1, unord) and not (fcw & 1):
                    line += DEV
                out.write(line.rstrip() + "\n")
                n += 1
    for asm, tab in MEMF:
        out.write("# %s\n" % asm)
        for st0 in (None, ONE, DEN, SNAN, QNAN):
            for key, (hexb, km) in tab.items():
                for fcw in FCWS:
                    k0 = KIND[st0]
                    line = "%s | fcw=0x%04X fsw=0x%04X %s m+0x8000=%s" % (asm, fcw, FSW, state(st0, None), hexb)
                    line = line.replace("  ", " ")
                    if k0 != "empty" and raises_ia(k0, km, False) and not (fcw & 1):
                        line += DEV
                    out.write(line + "\n")
                    n += 1
    for asm, tab in MEMI:
        out.write("# %s (no IM rule: \"unordered\" whatever FCW.IM)\n" % asm)
        for st0 in (None, ONE, NEG, DEN, SNAN, QNAN, UNNORM):
            for key, (hexb, km) in tab.items():
                for fcw in FCWS:
                    line = "%s | fcw=0x%04X fsw=0x%04X %s m+0x8000=%s" % (asm, fcw, FSW, state(st0, None), hexb)
                    out.write(line.replace("  ", " ") + "\n")
                    n += 1
    for asm in ("ftst", "fxam"):
        out.write("# %s%s\n" % (asm, " (no IM rule)" if asm == "ftst" else " (no exceptions; empty = C3 C0)"))
        for st0 in ST0_ONLY:
            for fcw in FCWS:
                line = "%s | fcw=0x%04X fsw=0x%04X %s" % (asm, fcw, FSW, state(st0, None))
                out.write(line.rstrip() + "\n")
                n += 1
    # an empty ST(0) holding a negative value: FXAM C1 is its sign (the register content)
    out.write("# fxam: empty ST(0) whose register holds a negative value (ftw marks it empty)\n")
    for fcw in (0x037F, 0x037C):
        out.write("fxam | fcw=0x%04X fsw=0x%04X st0=%s ftw=0x00\n" % (fcw, FSW, NEG))
        n += 1
    sys.stderr.write("cases: %d\n" % n)


if __name__ == "__main__":
    main()
