"""Generates NoVmp's Visual Studio 2022 build (no CMake): one solution, every dependency built
statically from the in-tree sources.

    NoVmp.sln
      NoVmp                       NoVmp/NoVmp.vcxproj
      Dependencies/capstone       msvc/capstone.vcxproj   (VTIL-Core/Dependencies/capstone)
      Dependencies/keystone       msvc/keystone.vcxproj   (VTIL-Core/Dependencies/keystone)
      Dependencies/unicorn        msvc/unicorn.vcxproj    (unicorn, x86 target)
      VTIL/VTIL-Common            msvc/VTIL-Common.vcxproj  ... and VTIL-SymEx/-Architecture/-Compiler

Source lists come from the trees themselves (and, for Capstone/Unicorn, the file lists in their
upstream build scripts, read as data), so after `git pull` in any dependency just re-run:

    python msvc/generate_projects.py
"""
import os
import re
import sys
import uuid
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VTIL = os.path.join(ROOT, "VTIL-Core")
DEPS = os.path.join(VTIL, "Dependencies")
CAPSTONE = os.path.join(DEPS, "capstone")
KEYSTONE = os.path.join(DEPS, "keystone")
KEYSTONE_CFG = os.path.join(DEPS, "keystone_config", "include")
UNICORN = os.path.join(ROOT, "unicorn")
LINUXPE = os.path.join(ROOT, "linux-pe", "includes")
NOVMP_DIR = os.path.join(ROOT, "NoVmp")
GENERATED = os.path.join(HERE, "generated")

CONFIGS = ("Debug", "Release")
PLATFORM = "x64"
TOOLSET = "v143"
NOVMP_GUID = "{C93BF114-7A97-45E1-8DA3-638AFDEDE25A}"  # keep upstream NoVmp's project GUID
VCXPROJ_TYPE = "{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}"
FOLDER_TYPE = "{2150E333-8FDC-42A3-9474-1A3956D46DE8}"


def log(msg):
    print(msg, flush=True)


def guid(name):
    return "{" + str(uuid.uuid5(uuid.NAMESPACE_URL, "novmp-msvc/" + name)).upper() + "}"


def files_under(base, exts, exclude_dirs=()):
    out = []
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in exclude_dirs and not d.startswith(".")]
        for f in filenames:
            if f.lower().endswith(exts):
                out.append(os.path.join(dirpath, f))
    return sorted(out)


def cmake_list(text, head):
    """Tokens of the first `head ... )` block in an upstream build script (read as data)."""
    m = re.search(re.escape(head) + r"\s+([^)]*)\)", text)
    if not m:
        sys.exit("generate_projects: cannot find '%s' in upstream build script" % head)
    return [t for t in m.group(1).split() if not t.startswith("#")]


def require(paths, what):
    missing = [p for p in paths if not os.path.exists(p)]
    if missing:
        sys.exit("generate_projects: %s lists files that do not exist:\n  " % what + "\n  ".join(missing))
    return paths


class Project:
    def __init__(self, name, path, kind, charset="MultiByte", project_guid=None):
        self.name = name
        self.path = path
        self.dir = os.path.dirname(path)
        self.kind = kind                    # StaticLibrary | Application
        self.charset = charset
        self.guid = project_guid or guid(name)
        self.sources = []                   # (path, {metadata})
        self.headers = []
        self.others = []                    # (tag, path)
        self.masm = []
        self.includes = []
        self.defines = []
        self.disable_warnings = []
        self.warning_level = "Level3"
        self.cpp_std = None                 # e.g. stdcpplatest
        self.c_std = None                   # e.g. stdc11
        self.conformance = None             # True -> /permissive-
        self.options = []
        self.link_options = []
        self.refs = []

    def rel(self, p):
        return os.path.relpath(p, self.dir)

    def obj_name(self, p):
        r = os.path.relpath(p, ROOT)
        flat = re.sub(r"[\\/:.]+", "_", os.path.splitext(r)[0])
        return "$(IntDir)" + flat + ".obj"

    def write(self):
        x = []
        a = x.append
        a('<?xml version="1.0" encoding="utf-8"?>')
        a("<!-- Generated by msvc/generate_projects.py - edit the generator, not this file. -->")
        a('<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">')
        a('  <ItemGroup Label="ProjectConfigurations">')
        for c in CONFIGS:
            a('    <ProjectConfiguration Include="%s|%s"><Configuration>%s</Configuration><Platform>%s</Platform></ProjectConfiguration>' % (c, PLATFORM, c, PLATFORM))
        a("  </ItemGroup>")
        a('  <PropertyGroup Label="Globals">')
        a("    <VCProjectVersion>17.0</VCProjectVersion>")
        a("    <ProjectGuid>%s</ProjectGuid>" % self.guid)
        a("    <RootNamespace>%s</RootNamespace>" % escape(self.name.replace("-", "_")))
        a("    <ProjectName>%s</ProjectName>" % escape(self.name))
        a("    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>")
        a("    <Keyword>Win32Proj</Keyword>")
        a("  </PropertyGroup>")
        a('  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />')
        for c in CONFIGS:
            a('  <PropertyGroup Condition="\'$(Configuration)|$(Platform)\'==\'%s|%s\'" Label="Configuration">' % (c, PLATFORM))
            a("    <ConfigurationType>%s</ConfigurationType>" % self.kind)
            a("    <UseDebugLibraries>%s</UseDebugLibraries>" % ("true" if c == "Debug" else "false"))
            a("    <PlatformToolset>%s</PlatformToolset>" % TOOLSET)
            a("    <CharacterSet>%s</CharacterSet>" % self.charset)
            a("    <WholeProgramOptimization>false</WholeProgramOptimization>")
            a("  </PropertyGroup>")
        a('  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />')
        a('  <ImportGroup Label="ExtensionSettings">')
        if self.masm:
            a('    <Import Project="$(VCTargetsPath)\\BuildCustomizations\\masm.props" />')
        a("  </ImportGroup>")
        a('  <ImportGroup Label="PropertySheets">')
        a('    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists(\'$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\')" Label="LocalAppDataPlatform" />')
        a("  </ImportGroup>")
        root_rel = os.path.relpath(ROOT, self.dir)
        a("  <PropertyGroup>")
        a("    <OutDir>$(MSBuildThisFileDirectory)%s\\build\\$(Platform)\\$(Configuration)\\</OutDir>" % root_rel)
        a("    <IntDir>$(MSBuildThisFileDirectory)%s\\build\\$(Platform)\\$(Configuration)\\obj\\$(ProjectName)\\</IntDir>" % root_rel)
        a("  </PropertyGroup>")
        for c in CONFIGS:
            dbg = c == "Debug"
            a('  <ItemDefinitionGroup Condition="\'$(Configuration)|$(Platform)\'==\'%s|%s\'">' % (c, PLATFORM))
            a("    <ClCompile>")
            a("      <WarningLevel>%s</WarningLevel>" % self.warning_level)
            if self.disable_warnings:
                a("      <DisableSpecificWarnings>%s;%%(DisableSpecificWarnings)</DisableSpecificWarnings>" % ";".join(self.disable_warnings))
            a("      <SDLCheck>false</SDLCheck>")
            defs = list(self.defines) + (["_DEBUG"] if dbg else ["NDEBUG"])
            a("      <PreprocessorDefinitions>%s;%%(PreprocessorDefinitions)</PreprocessorDefinitions>" % escape(";".join(defs)))
            if self.includes:
                a("      <AdditionalIncludeDirectories>%s;%%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>" % escape(";".join(self.rel(p) for p in self.includes)))
            if self.conformance is not None:
                a("      <ConformanceMode>%s</ConformanceMode>" % ("true" if self.conformance else "false"))
            if self.cpp_std:
                a("      <LanguageStandard>%s</LanguageStandard>" % self.cpp_std)
            if self.c_std:
                a("      <LanguageStandard_C>%s</LanguageStandard_C>" % self.c_std)
            a("      <RuntimeLibrary>%s</RuntimeLibrary>" % ("MultiThreadedDebug" if dbg else "MultiThreaded"))
            a("      <Optimization>%s</Optimization>" % ("Disabled" if dbg else "MaxSpeed"))
            if not dbg:
                a("      <FunctionLevelLinking>true</FunctionLevelLinking>")
                a("      <IntrinsicFunctions>true</IntrinsicFunctions>")
            a("      <MultiProcessorCompilation>true</MultiProcessorCompilation>")
            a("      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>")
            if self.options:
                a("      <AdditionalOptions>%s %%(AdditionalOptions)</AdditionalOptions>" % escape(" ".join(self.options)))
            a("    </ClCompile>")
            if self.kind == "Application":
                a("    <Link>")
                a("      <SubSystem>Console</SubSystem>")
                a("      <GenerateDebugInformation>true</GenerateDebugInformation>")
                if not dbg:
                    a("      <EnableCOMDATFolding>true</EnableCOMDATFolding>")
                    a("      <OptimizeReferences>true</OptimizeReferences>")
                if self.link_options:
                    a("      <AdditionalOptions>%s %%(AdditionalOptions)</AdditionalOptions>" % escape(" ".join(self.link_options)))
                a("    </Link>")
            a("  </ItemDefinitionGroup>")
        a("  <ItemGroup>")
        for p, meta in self.sources:
            a('    <ClCompile Include="%s">' % escape(self.rel(p)))
            a("      <ObjectFileName>%s</ObjectFileName>" % escape(self.obj_name(p)))
            if meta.get("defines"):
                a("      <PreprocessorDefinitions>%s;%%(PreprocessorDefinitions)</PreprocessorDefinitions>" % escape(";".join(meta["defines"])))
            if meta.get("includes"):
                a("      <AdditionalIncludeDirectories>%s;%%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>" % escape(";".join(self.rel(i) for i in meta["includes"])))
            if meta.get("force_include"):
                a("      <ForcedIncludeFiles>%s;%%(ForcedIncludeFiles)</ForcedIncludeFiles>" % escape(meta["force_include"]))
            a("    </ClCompile>")
        a("  </ItemGroup>")
        if self.headers:
            a("  <ItemGroup>")
            for p in self.headers:
                a('    <ClInclude Include="%s" />' % escape(self.rel(p)))
            a("  </ItemGroup>")
        if self.others:
            a("  <ItemGroup>")
            for tag, p in self.others:
                a('    <%s Include="%s" />' % (tag, escape(self.rel(p))))
            a("  </ItemGroup>")
        if self.masm:
            a("  <ItemGroup>")
            for p in self.masm:
                a('    <MASM Include="%s" />' % escape(self.rel(p)))
            a("  </ItemGroup>")
        if self.refs:
            a("  <ItemGroup>")
            for r in self.refs:
                a('    <ProjectReference Include="%s"><Project>%s</Project></ProjectReference>' % (escape(self.rel(r.path)), r.guid))
            a("  </ItemGroup>")
        a('  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />')
        a('  <ImportGroup Label="ExtensionTargets">')
        if self.masm:
            a('    <Import Project="$(VCTargetsPath)\\BuildCustomizations\\masm.targets" />')
        a("  </ImportGroup>")
        a("</Project>")
        os.makedirs(self.dir, exist_ok=True)
        with open(self.path, "w", encoding="utf-8", newline="\r\n") as f:
            f.write("\n".join(x) + "\n")
        self.write_filters()
        log("  wrote %-28s %4d sources, %4d headers" % (os.path.relpath(self.path, ROOT), len(self.sources), len(self.headers)))

    def write_filters(self):
        """Solution-explorer folders mirroring the source tree."""
        entries = [("ClCompile", p) for p, _ in self.sources] + [("ClInclude", p) for p in self.headers] + \
                  [(t, p) for t, p in self.others] + [("MASM", p) for p in self.masm]
        base = os.path.commonpath([os.path.dirname(p) for _, p in entries]) if entries else self.dir
        folders = set()
        rows = []
        for tag, p in entries:
            d = os.path.relpath(os.path.dirname(p), base)
            d = "" if d == "." else d
            parts = d.split(os.sep) if d else []
            for i in range(1, len(parts) + 1):
                folders.add("\\".join(parts[:i]))
            rows.append((tag, p, "\\".join(parts)))
        x = ['<?xml version="1.0" encoding="utf-8"?>',
             '<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">',
             "  <ItemGroup>"]
        for f in sorted(folders):
            x.append('    <Filter Include="%s"><UniqueIdentifier>%s</UniqueIdentifier></Filter>' % (escape(f), guid(self.name + "/" + f)))
        x.append("  </ItemGroup>")
        x.append("  <ItemGroup>")
        for tag, p, folder in rows:
            if folder:
                x.append('    <%s Include="%s"><Filter>%s</Filter></%s>' % (tag, escape(self.rel(p)), escape(folder), tag))
            else:
                x.append('    <%s Include="%s" />' % (tag, escape(self.rel(p))))
        x.append("  </ItemGroup>")
        x.append("</Project>")
        with open(self.path + ".filters", "w", encoding="utf-8", newline="\r\n") as f:
            f.write("\n".join(x) + "\n")


# ── Capstone ─────────────────────────────────────────────────────────────────────────────────

def make_capstone():
    text = open(os.path.join(CAPSTONE, "CMakeLists.txt"), encoding="utf-8").read()
    archs = cmake_list(text, "set(SUPPORTED_ARCHITECTURES")
    srcs = cmake_list(text, "set(SOURCES_ENGINE")
    for m in re.finditer(r"set\(\s*SOURCES_([A-Z0-9_]+)\s+([^)]*)\)", text):
        if m.group(1) == "ENGINE":
            continue
        srcs += [t for t in m.group(2).split() if t.endswith(".c") and not t.startswith("${")]
    has = re.findall(r"if\(CAPSTONE_([A-Z0-9_]+)_SUPPORT\)\s*\n\s*add_definitions\(-D(CAPSTONE_HAS_[A-Z0-9_]+)\)", text)
    srcs = require(sorted(set(os.path.join(CAPSTONE, s.replace("/", os.sep)) for s in srcs)), "capstone")

    p = Project("capstone", os.path.join(HERE, "capstone.vcxproj"), "StaticLibrary")
    p.sources = [(s, {}) for s in srcs]
    p.headers = files_under(os.path.join(CAPSTONE, "include", "capstone"), (".h",))
    p.includes = [os.path.join(CAPSTONE, "include"), CAPSTONE]
    p.defines = ["CAPSTONE_USE_SYS_DYN_MEM", "_CRT_SECURE_NO_WARNINGS"] + \
                ["CAPSTONE_%s_SUPPORT" % a for a in archs] + sorted(set(d for _, d in has))
    p.warning_level = "Level1"
    p.c_std = "stdc11"
    log("capstone: %d architectures, %d sources" % (len(archs), len(srcs)))
    return p


# ── Keystone ─────────────────────────────────────────────────────────────────────────────────

def make_keystone():
    llvm_cmake = open(os.path.join(KEYSTONE, "llvm", "CMakeLists.txt"), encoding="utf-8").read()
    targets = cmake_list(llvm_cmake, "set(LLVM_ALL_TARGETS")
    targets = [t for t in targets if os.path.isdir(os.path.join(KEYSTONE, "llvm", "lib", "Target", t))]

    # Target registration fragments LLVM's build would configure from the .def.in templates
    cfg_out = os.path.join(GENERATED, "keystone", "include", "llvm", "Config")
    os.makedirs(cfg_out, exist_ok=True)
    for name, macro, var in (("AsmParsers.def", "LLVM_ASM_PARSER", "LLVM_ENUM_ASM_PARSERS"),
                             ("Targets.def", "LLVM_TARGET", "LLVM_ENUM_TARGETS")):
        tmpl = open(os.path.join(KEYSTONE, "llvm", "include", "llvm", "Config", name + ".in"), encoding="utf-8").read()
        body = "".join("%s(%s)\n" % (macro, t) for t in targets)
        with open(os.path.join(cfg_out, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(tmpl.replace("@%s@" % var, body))

    srcs = files_under(os.path.join(KEYSTONE, "llvm"), (".cpp", ".c"))
    p = Project("keystone", os.path.join(HERE, "keystone.vcxproj"), "StaticLibrary")
    p.sources = [(s, {}) for s in srcs]
    p.headers = files_under(os.path.join(KEYSTONE, "include", "keystone"), (".h",))
    p.includes = [os.path.join(KEYSTONE, "include"), os.path.join(KEYSTONE, "llvm", "include"),
                  KEYSTONE_CFG, os.path.join(GENERATED, "keystone", "include")] + \
                 [os.path.join(KEYSTONE, "llvm", "lib", "Target", t) for t in targets]
    p.defines = ["KEYSTONE_STATIC", "_CRT_SECURE_NO_WARNINGS"] + ["LLVM_ENABLE_ARCH_%s" % t for t in targets]
    p.warning_level = "TurnOffAllWarnings"
    p.disable_warnings = ["4244", "4267"]
    p.cpp_std = "stdcpp14"
    p.conformance = False
    log("keystone: targets %s, %d sources" % (" ".join(targets), len(srcs)))
    return p


# ── Unicorn (x86 target) ─────────────────────────────────────────────────────────────────────

def make_unicorn():
    text = open(os.path.join(UNICORN, "CMakeLists.txt"), encoding="utf-8").read()
    u = lambda rel: os.path.join(UNICORN, rel.replace("/", os.sep))

    arch_common = cmake_list(text, "set(UNICORN_ARCH_COMMON")
    x86 = [t for t in cmake_list(text, "add_library(x86_64-softmmu STATIC") if t.endswith(".c")]
    core = cmake_list(text, "set(UNICORN_SRCS")
    common = cmake_list(text, "set(UNICORN_COMMON_SRCS")
    # Windows-only additions from the MSVC branch (the POSIX branch is skipped)
    for m in re.finditer(r"set\(UNICORN_COMMON_SRCS\s+\$\{UNICORN_COMMON_SRCS\}\s+([^)]*)\)", text):
        common += [t for t in m.group(1).split() if t.endswith(".c") and "win32" in t]
    asm = [t for t in re.findall(r"(qemu/util/[\w-]+win32\.asm)", text)]

    target_srcs = require([u(s) for s in arch_common + x86], "unicorn x86 target")
    core_srcs = require([u(s) for s in core + common], "unicorn core/common")
    asm_srcs = require(sorted(set(u(s) for s in asm)), "unicorn asm")

    p = Project("unicorn", os.path.join(HERE, "unicorn.vcxproj"), "StaticLibrary")
    # QEMU's per-target sources: renaming header forced in, NEED_CPU_H, target config first
    # Forced by name, as upstream does: a relative /FI path would resolve from each source's dir
    target_meta = {"defines": ["NEED_CPU_H"], "force_include": "x86_64.h",
                   "includes": [u("msvc/x86_64-softmmu"), u("qemu/target/i386")]}
    core_meta = {"defines": ["UNICORN_HAS_X86"]}
    p.sources = [(s, dict(target_meta)) for s in target_srcs] + [(s, dict(core_meta)) for s in core_srcs]
    p.headers = files_under(os.path.join(UNICORN, "include", "unicorn"), (".h",))
    p.masm = asm_srcs
    p.includes = [u("msvc"), u("glib_compat"), u("qemu"), u("qemu/include"), u("include"), u("qemu/tcg"), u("qemu/tcg/i386")]
    p.defines = ["inline=__inline", "__func__=__FUNCTION__", "_CRT_SECURE_NO_WARNINGS", "WIN32_LEAN_AND_MEAN",
                 "__x86_64__", "WIN32_ENABLE_VEH"]
    p.disable_warnings = ["4018", "4098", "4244", "4267"]
    log("unicorn: %d target sources, %d core/common sources, %d asm" % (len(target_srcs), len(core_srcs), len(asm_srcs)))
    return p


# ── VTIL ─────────────────────────────────────────────────────────────────────────────────────

VTIL_LIBS = ("VTIL-Common", "VTIL-SymEx", "VTIL-Architecture", "VTIL-Compiler")
VTIL_INCLUDES = [os.path.join(VTIL, d, "includes") for d in ("VTIL", "VTIL-Common", "VTIL-SymEx", "VTIL-Architecture", "VTIL-Compiler")]
# CAPSTONE_AARCH64_COMPAT_HEADER: Capstone 6 renamed ARM64 to AArch64; VTIL's arm64 code uses the
# old names, which Capstone's own compatibility header provides.
VTIL_DEFINES = ["WIN32_LEAN_AND_MEAN", "NOMINMAX", "KEYSTONE_STATIC", "CAPSTONE_AARCH64_COMPAT_HEADER"]


def make_vtil(name, deps):
    d = os.path.join(VTIL, name)
    p = Project(name, os.path.join(HERE, name + ".vcxproj"), "StaticLibrary", charset="Unicode")
    p.sources = [(s, {}) for s in files_under(d, (".cpp",))]
    p.headers = files_under(d, (".hpp", ".h"))
    p.includes = VTIL_INCLUDES + [os.path.join(CAPSTONE, "include"), os.path.join(KEYSTONE, "include")]
    p.defines = VTIL_DEFINES + ["_LIB"]
    p.cpp_std = "stdcpplatest"
    p.conformance = True               # /permissive-, as VTIL's MSVC build uses
    p.options = ["/bigobj"]
    p.refs = deps
    return p


# ── NoVmp ────────────────────────────────────────────────────────────────────────────────────

def make_novmp(libs):
    p = Project("NoVmp", os.path.join(NOVMP_DIR, "NoVmp.vcxproj"), "Application", charset="Unicode", project_guid=NOVMP_GUID)
    p.sources = [(s, {}) for s in files_under(NOVMP_DIR, (".cpp",))]
    p.headers = files_under(NOVMP_DIR, (".hpp", ".h"))
    p.others = [("ResourceCompile", s) for s in files_under(NOVMP_DIR, (".rc",))] + \
               [("Image", s) for s in files_under(NOVMP_DIR, (".ico",))]
    p.includes = VTIL_INCLUDES + [LINUXPE, os.path.join(CAPSTONE, "include"), os.path.join(KEYSTONE, "include"),
                                  os.path.join(UNICORN, "include")]
    p.defines = VTIL_DEFINES + ["_CONSOLE"]
    p.cpp_std = "stdcpplatest"
    p.conformance = True
    p.options = ["/bigobj"]
    p.link_options = ["/STACK:67108864"]   # VTIL's static initialization needs a 64 MiB stack
    p.refs = libs
    return p


def write_solution(projects, folders):
    path = os.path.join(ROOT, "NoVmp.sln")
    x = ["", "Microsoft Visual Studio Solution File, Format Version 12.00", "# Visual Studio Version 17",
         "VisualStudioVersion = 17.0.31903.59", "MinimumVisualStudioVersion = 10.0.40219.1"]
    for p in projects:
        x.append('Project("%s") = "%s", "%s", "%s"' % (VCXPROJ_TYPE, p.name, os.path.relpath(p.path, ROOT), p.guid))
        x.append("EndProject")
    for fname in folders:
        fg = guid("folder/" + fname)
        x.append('Project("%s") = "%s", "%s", "%s"' % (FOLDER_TYPE, fname, fname, fg))
        x.append("EndProject")
    x.append("Global")
    x.append("\tGlobalSection(SolutionConfigurationPlatforms) = preSolution")
    for c in CONFIGS:
        x.append("\t\t%s|%s = %s|%s" % (c, PLATFORM, c, PLATFORM))
    x.append("\tEndGlobalSection")
    x.append("\tGlobalSection(ProjectConfigurationPlatforms) = postSolution")
    for p in projects:
        for c in CONFIGS:
            x.append("\t\t%s.%s|%s.ActiveCfg = %s|%s" % (p.guid, c, PLATFORM, c, PLATFORM))
            x.append("\t\t%s.%s|%s.Build.0 = %s|%s" % (p.guid, c, PLATFORM, c, PLATFORM))
    x.append("\tEndGlobalSection")
    x.append("\tGlobalSection(SolutionProperties) = preSolution")
    x.append("\t\tHideSolutionNode = FALSE")
    x.append("\tEndGlobalSection")
    x.append("\tGlobalSection(NestedProjects) = preSolution")
    for fname, members in folders.items():
        for p in members:
            x.append("\t\t%s = %s" % (p.guid, guid("folder/" + fname)))
    x.append("\tEndGlobalSection")
    x.append("\tGlobalSection(ExtensibilityGlobals) = postSolution")
    x.append("\t\tSolutionGuid = %s" % guid("solution"))
    x.append("\tEndGlobalSection")
    x.append("EndGlobal")
    with open(path, "w", encoding="utf-8-sig", newline="\r\n") as f:
        f.write("\n".join(x) + "\n")
    log("  wrote NoVmp.sln (%d projects)" % len(projects))


def main():
    log("NoVmp MSVC project generator (root %s)" % ROOT)
    capstone = make_capstone()
    keystone = make_keystone()
    unicorn = make_unicorn()
    common = make_vtil("VTIL-Common", [capstone, keystone])
    symex = make_vtil("VTIL-SymEx", [common])
    arch = make_vtil("VTIL-Architecture", [common, symex])
    compiler = make_vtil("VTIL-Compiler", [common, symex, arch])
    vtil = [common, symex, arch, compiler]
    deps = [capstone, keystone, unicorn]
    novmp = make_novmp(vtil + deps)
    for p in [novmp] + deps + vtil:
        p.write()
    write_solution([novmp] + deps + vtil, {"Dependencies": deps, "VTIL": vtil})
    log("done")


if __name__ == "__main__":
    main()
